//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTAnalyticsClient/_TtC18DVTAnalyticsClient38AnalyticsProcessorUsagePointIdentifier.h>

@class NSArray, NSDictionary;

@interface _TtC18DVTAnalyticsClient38AnalyticsProcessorUsagePointIdentifier (DVTAnalyticsClient2)
@property(nonatomic, readonly) NSDictionary *parameters;
@property(nonatomic, readonly) NSArray *pathComponents;
@end

