//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DVTAnalyticsData : NSObject
{
    NSString *_platform;
    NSString *_isBeta;
}

@property(retain, nonatomic) NSString *isBeta; // @synthesize isBeta=_isBeta;
- (void).cxx_destruct;
@property(retain) NSString *platform; // @synthesize platform=_platform;

@end

