//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _IDELocalizationExportTargetLanguage : NSObject
{
    BOOL _included;
    BOOL _developmentRegion;
    NSString *_displayName;
    NSString *_localeIdentifier;
}

+ (id)keyPathsForValuesAffectingDisplayName;
+ (id)keyPathsForValuesAffectingIncluded;
+ (id)keyPathsForValuesAffectingCanSetIncluded;
@property(getter=isDevelopmentRegion) BOOL developmentRegion; // @synthesize developmentRegion=_developmentRegion;
@property(copy) NSString *localeIdentifier; // @synthesize localeIdentifier=_localeIdentifier;
@property(copy) NSString *displayName; // @synthesize displayName=_displayName;
@property(nonatomic, getter=isIncluded) BOOL included; // @synthesize included=_included;
- (void).cxx_destruct;
@property(readonly, copy) NSString *formattedDisplayName;
@property(readonly) BOOL canSetIncluded;

@end

