//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSImageView, NSTextField;

@interface _TtC6IDEKit32IDEAccountPrefsPaneTableCellView : NSTableCellView
{
    // Error parsing type: , name: statusImageView
    // Error parsing type: , name: subtitleTextField
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *subtitleTextField; // @synthesize subtitleTextField;
@property(nonatomic, retain) NSImageView *statusImageView; // @synthesize statusImageView;

@end

