//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSString;

@interface _TtC6IDEKit36IDESourceControlPendingHostedAccount : NSObject
{
    // Error parsing type: , name: accountTitle
    // Error parsing type: , name: accountSubTitle
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long accountReachability;
@property(nonatomic, readonly) BOOL accountEnabled;
@property(nonatomic, readonly) NSImage *accountImage;
@property(nonatomic, copy) NSString *accountSubTitle; // @synthesize accountSubTitle;
@property(nonatomic, copy) NSString *accountTitle; // @synthesize accountTitle;

@end

