//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6IDEKit44IDESourceControlWorkingCopyOperationCellInfo : SwiftObject
{
    // Error parsing type: , name: selected
    // Error parsing type: , name: enabled
    // Error parsing type: , name: menu
    // Error parsing type: , name: selectedItem
    // Error parsing type: , name: selectedBranch
    // Error parsing type: , name: selectedRemote
    // Error parsing type: , name: remotes
}

@end

