//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;
@protocol _TtP6IDEKit26AnyExplorableJumpBarHandle_;

@interface _TtC6IDEKit44ExplorableJumpBarControllerBindingsInterface : NSObject
{
    // Error parsing type: , name: didSetCallback
    // Error parsing type: , name: rootSiblings
    // Error parsing type: , name: selection
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, retain) id <_TtP6IDEKit26AnyExplorableJumpBarHandle_> selection; // @synthesize selection;
@property(nonatomic, copy) NSArray *rootSiblings; // @synthesize rootSiblings;

@end

