//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMenuItem, _TtC6IDEKit33IDESourceControlCommitAndPushInfo;

@interface _TtC6IDEKit43IDESourceControlCommitAndPushMenuController : NSObject
{
    // Error parsing type: , name: workingCopy
    // Error parsing type: , name: info
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _TtC6IDEKit33IDESourceControlCommitAndPushInfo *commitAndPushInfo;
- (void)buildMenu:(CDUnknownBlockType)arg1;
- (id)initWithWorkingCopy:(id)arg1;
@property(nonatomic, retain) NSMenuItem *selectedItem;

@end

