//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEBreakpointIcon : NSObject
{
    struct CGSize _size;
}

+ (double)tipLengthForBreakpointHeight:(double)arg1;
+ (id)shared;
- (id)_createBreakpointPathsWithFrame:(struct CGRect)arg1 breakpointModified:(BOOL)arg2;
- (void)_drawModifiedBreakpointIndicatorPath:(id)arg1;
- (void)_drawFullBreakpointPath:(id)arg1 backgroundFillColor:(id)arg2 fillColor:(id)arg3 strokeColor:(id)arg4;
- (id)_strokeColorForFillColor:(id)arg1;
- (id)_fillColorForActive:(BOOL)arg1 enabled:(BOOL)arg2;
- (id)_backgroundFillColor:(int)arg1;
- (id)_imageKeyForActive:(BOOL)arg1 enabled:(BOOL)arg2 modified:(BOOL)arg3 bordered:(BOOL)arg4 backgroundFill:(int)arg5 size:(struct CGSize)arg6;
- (id)cachedImageForBreakpointsActivated:(BOOL)arg1 breakpointEnabled:(BOOL)arg2 breakpointModified:(BOOL)arg3;
- (id)cachedImageForActivated:(BOOL)arg1 enabled:(BOOL)arg2 modified:(BOOL)arg3 bordered:(BOOL)arg4 backgroundFill:(int)arg5 size:(struct CGSize)arg6;
- (id)cachedImageForActivated:(BOOL)arg1 enabled:(BOOL)arg2 modified:(BOOL)arg3 bordered:(BOOL)arg4 size:(struct CGSize)arg5;
- (id)initWithSize:(struct CGSize)arg1 includeBottomHighlight:(BOOL)arg2 useDarkerBorderColor:(BOOL)arg3;

@end

