//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSBox, NSTextField;

@interface IDEDistributionTableCellView : NSTableCellView
{
    NSBox *_bottomBorder;
    NSTextField *_titleField;
}

@property(retain) NSTextField *titleField; // @synthesize titleField=_titleField;
@property(retain) NSBox *bottomBorder; // @synthesize bottomBorder=_bottomBorder;
- (void).cxx_destruct;
- (double)heightAccomodatingTextFieldWrappingWithColumnWidth:(double)arg1;

@end

