//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/NSPathCellDelegate-Protocol.h>

@class IDEPathCell, IDEPathComponentCell, NSArray, NSMenu, NSMenuItem, NSObject, NSString;
@protocol IDEPathCellItem;

@protocol IDEPathCellDelegate <NSPathCellDelegate>

@optional
- (void)pathCell:(IDEPathCell *)arg1 didEndDragForComponentCell:(IDEPathComponentCell *)arg2;
- (BOOL)pathCell:(IDEPathCell *)arg1 beginDragForComponentCell:(IDEPathComponentCell *)arg2;
- (NSString *)pathCell:(IDEPathCell *)arg1 toolTipForPathComponentCell:(IDEPathComponentCell *)arg2 atIndex:(unsigned long long)arg3;
- (NSString *)pathCell:(IDEPathCell *)arg1 accessibilityDescriptionForPathComponentCell:(IDEPathComponentCell *)arg2 atIndex:(unsigned long long)arg3;
- (unsigned long long)pathCell:(IDEPathCell *)arg1 textAlignmentOfTitleForPathComponentCell:(IDEPathComponentCell *)arg2 atIndex:(unsigned long long)arg3;
- (NSString *)pathCell:(IDEPathCell *)arg1 titleForPathComponentCell:(IDEPathComponentCell *)arg2 atIndex:(unsigned long long)arg3;
- (NSString *)pathCellNoSelectionTitle;
- (struct CGPoint)pathCell:(IDEPathCell *)arg1 adjustPopupMenuLocation:(struct CGPoint)arg2;
- (NSMenuItem *)pathCell:(IDEPathCell *)arg1 menuItemForItem:(NSObject<IDEPathCellItem> *)arg2 defaultMenuItem:(NSMenuItem *)arg3;
- (void)pathCell:(IDEPathCell *)arg1 didUpdateMenu:(NSMenu *)arg2;
- (BOOL)pathCell:(IDEPathCell *)arg1 performAlternateReveal:(NSObject<IDEPathCellItem> *)arg2 fromFrame:(struct CGRect)arg3;
- (BOOL)pathCell:(IDEPathCell *)arg1 shouldEnableSelection:(NSObject<IDEPathCellItem> *)arg2;
- (BOOL)pathCell:(IDEPathCell *)arg1 shouldInitiallyShowMenuSearch:(NSObject<IDEPathCellItem> *)arg2;
- (NSArray *)pathCell:(IDEPathCell *)arg1 childItemsForItem:(NSObject<IDEPathCellItem> *)arg2;
- (BOOL)pathCell:(IDEPathCell *)arg1 shouldPopUpMenuForPathComponentCell:(IDEPathComponentCell *)arg2 item:(NSObject<IDEPathCellItem> *)arg3;
- (BOOL)pathCell:(IDEPathCell *)arg1 shouldSeparateDisplayOfChildItemsForItem:(NSObject<IDEPathCellItem> *)arg2;
- (BOOL)pathCell:(IDEPathCell *)arg1 shouldDisplayChildrenForItem:(NSObject<IDEPathCellItem> *)arg2;
- (void)pathCell:(IDEPathCell *)arg1 willDismissMenuDisplayingItems:(NSArray *)arg2;
- (void)pathCell:(IDEPathCell *)arg1 willDisplayChildren:(NSArray *)arg2 mostProximateChildItem:(NSObject<IDEPathCellItem> *)arg3;
@end

