//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBDeviceConfiguration, IBIdiom, IBMemberConfiguration, IBTargetRuntime;

@interface IBAbstractPreviewRecipe : NSObject
{
}

- (id)description;
@property(readonly) IBIdiom *idiom;
@property(readonly) IBDeviceConfiguration *deviceConfiguration;
@property(readonly) IBMemberConfiguration *memberConfiguration;
@property(readonly) IBTargetRuntime *targetRuntime;
- (id)propertyListRepresentation;
- (id)initWithPropertyList:(id)arg1;

@end

