//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEInterfaceBuilderKit/NSCopying-Protocol.h>

@class NSString;

@interface IBAbstractDocumentUnarchiverGroupMember : NSObject <NSCopying>
{
}

- (id)unarchiveAsObjectReferenceWithReferenceType:(id)arg1;
- (id)unarchiveAsObject;
- (void)unarchiveContentWithBlock:(CDUnknownBlockType)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly) NSString *elementName; // @dynamic elementName;
@property(readonly) NSString *key; // @dynamic key;

@end

