//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

@interface IBActionForwardingResponder : NSResponder
{
    id _target;
}

@property __weak id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;

@end

