//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBAutolayoutIssueOutlineItem.h>

@class IBAbstractLayoutConstraintAbstraction;

@interface IBAutolayoutConstraintAbstractionOutlineItem : IBAutolayoutIssueOutlineItem
{
    IBAbstractLayoutConstraintAbstraction *_abstraction;
}

@property(readonly, nonatomic) IBAbstractLayoutConstraintAbstraction *abstraction; // @synthesize abstraction=_abstraction;
- (void).cxx_destruct;
- (id)initWithConstraintAbstraction:(id)arg1;

@end

