//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEInspectorProperty.h>

@class IBICColorReferencePropertyChoice, IDEInspectorKeyPath, NSMenuItem, NSPopUpButton;

@interface IBColorReferenceProperty : IDEInspectorProperty
{
    IDEInspectorKeyPath *_choicesKeyPath;
    IDEInspectorKeyPath *_valueKeyPath;
    IDEInspectorKeyPath *_colorAppearanceKeyPath;
    IBICColorReferencePropertyChoice *_value;
    NSMenuItem *_selectedMenuItem;
    NSMenuItem *_multipleValuesMenuItem;
    BOOL _isShowingMultipleValues;
    NSPopUpButton *_popupButton;
}

@property(retain, nonatomic) NSPopUpButton *popupButton; // @synthesize popupButton=_popupButton;
- (void).cxx_destruct;
- (void)rebuildMenuContent;
- (void)refresh;
- (void)userDidChangeValue:(id)arg1;
- (void)setupRefreshTriggersAndConfigure;
- (double)baseline;

@end

