//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class IBDelegatedCanvasOverlay, NSView;

@protocol IBDelegatedCanvasOverlayDelegate <NSObject>
- (NSView *)delegatedCanvasOverlay:(IBDelegatedCanvasOverlay *)arg1 hitTest:(struct CGPoint)arg2 inCoordinatesSpaceOfView:(NSView *)arg3;
@end

