//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBQuadtree, NSArray, NSDictionary, NSMutableArray;

@interface IBHitDetectionMap : NSObject
{
    struct CGRect _boundingRect;
    NSMutableArray *_representedObjectRects;
    IBQuadtree *_quadtree;
    NSArray *_orderedKeys;
    NSDictionary *_keyToOrder;
}

+ (id)alwaysOnTopKey;
+ (id)alwaysOnBottomKey;
- (void).cxx_destruct;
- (long long)orderForKey:(id)arg1;
- (id)representedObjectAtPoint:(struct CGPoint)arg1;
- (void)buildIndexForOrderedObjects:(id)arg1;
- (void)addRepresentedObjectRect:(struct CGRect)arg1 representedObject:(id)arg2 forOrderingKey:(id)arg3 onLayer:(unsigned long long)arg4;

@end

