//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IBFoundation/IBICARImageSet.h>

@interface IBICARImageSet (InspectorAdditions)
- (void)setIbInspectedUnitName:(id)arg1;
- (id)ibInspectedUnitName;
- (void)setIbInspectedHeight:(id)arg1;
- (id)ibInspectedHeight;
- (void)setIbInspectedWidth:(double)arg1;
- (double)ibInspectedWidth;
@end

