//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IBFoundation/IBICSlottedAssetCollection.h>

#import <IDEInterfaceBuilderKit/IBICAssetWithSlottedChildrenDisplayAdditions_ONLY-Protocol.h>

@interface IBICSlottedAssetCollection (IBICAssetWithSlottedChildrenDisplayAdditionsAdaptation) <IBICAssetWithSlottedChildrenDisplayAdditions_ONLY>
- (id)createDefaultChildForNewSlot:(id)arg1 byModifyingSlot:(id)arg2;
- (id)mutateByAddingNewChild:(id)arg1 forSlot:(id)arg2 inDocument:(id)arg3;
- (id)mutateByAddingCopyOfChild:(id)arg1 usingSlot:(id)arg2 inDocument:(id)arg3;
@end

