//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface IBPlatformToolProxyQueue : NSObject
{
    NSMutableArray *_proxyList;
    NSMutableDictionary *_sessionIDToProxy;
    unsigned long long _nextAvailableIndex;
}

- (void).cxx_destruct;
- (id)description;
- (id)nextProxy;
- (id)toolProxyIncrementingBusyForSessionIdentifier:(id)arg1 includingAlreadyBusy:(BOOL)arg2;
- (void)registerTool:(id)arg1 forPossibleSessionIdentifier:(id)arg2;
@property(readonly) long long count;
- (void)addProxy:(id)arg1 registerSessionIdentifierIfNeeded:(id)arg2;
- (void)removeProxy:(id)arg1;
- (void)shutdownAllButOneAfterBlock:(CDUnknownBlockType)arg1;
- (void)shutdownAllAfterBlock:(CDUnknownBlockType)arg1;
- (void)shutdownAndRemoveProxy:(id)arg1;
- (void)shutdownToolsIdleForAtleast:(double)arg1;

@end

