//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBezierPath, NSImage;

@interface IBStructureAreaDockItemViewOpenIndicator : NSObject
{
    NSImage *_openIndicatorImage;
    NSBezierPath *_innerPath;
}

- (void).cxx_destruct;
- (id)imageDrawnForTheme:(id)arg1;
- (id)imageDrawnAsSelected:(BOOL)arg1 forTheme:(id)arg2;
- (id)image;
- (id)init;

@end

