//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class IBStructureViewController;

@protocol IBStructureViewControllerDelegate <NSObject>
- (void)structureViewController:(IBStructureViewController *)arg1 didChangeVisibility:(BOOL)arg2;
- (void)structureViewControllerDidChangeContentSize:(IBStructureViewController *)arg1;
@end

