//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBClassValueMarshaller : NSObject
{
}

+ (id)valueForKeyPath:(id)arg1 ofClassNamed:(id)arg2 targetRuntime:(id)arg3 toolDescription:(id)arg4 defaultValue:(id)arg5 context:(id)arg6 diagnosticsBlock:(CDUnknownBlockType)arg7;
+ (id)valueForKeyPath:(id)arg1 ofClassNamed:(id)arg2 targetRuntime:(id)arg3 deviceTypeDescription:(id)arg4 defaultValue:(id)arg5 context:(id)arg6 diagnosticsBlock:(CDUnknownBlockType)arg7;

@end

