//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBDocumentLiveViewsDispatcher.h>

@interface IBCocoaTouchDocumentLiveViewsDispatcher : IBDocumentLiveViewsDispatcher
{
}

- (void)sendDebugRequestsForView:(id)arg1 marshalledRepresentation:(id)arg2 tool:(id)arg3 queue:(id)arg4;

@end

