//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBUIStoryboardAbstractTriggeredSegue.h>

@interface IBCocoaTouchStoryboardPlaceholderSegue : IBUIStoryboardAbstractTriggeredSegue
{
}

+ (id)ibDefaultImageForInstance:(id)arg1 targetRuntime:(id)arg2;
+ (BOOL)shouldBeUserVisibleInDocument:(id)arg1;
+ (id)classIdentifier;
+ (id)placeholderSegueFromSegue:(id)arg1;
- (BOOL)shouldArchiveKind;
- (id)segueForInheritableMetrics;
- (id)instantiateSegueTemplate;
- (BOOL)_isPreviewPhase;
- (id)badgeImage;
- (id)kindDisplayName;

@end

