//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBUISimulatedMetricsExtendedEdgeProvider-Protocol.h>

@class IBUISimulatedBarMetrics, IBUISimulatedMetricsContainer, IBUISimulatedOrientationMetrics, IBUISimulatedSizeMetrics, IBUISimulatedStatusBarMetrics;

@protocol IBUISimulatedMetricsObject <IBUISimulatedMetricsExtendedEdgeProvider>
@property(copy) IBUISimulatedSizeMetrics *simulatedDestinationMetrics;
@property(copy) IBUISimulatedOrientationMetrics *simulatedOrientationMetrics;
@property(copy) IBUISimulatedBarMetrics *simulatedBottomBarMetrics;
@property(copy) IBUISimulatedBarMetrics *simulatedTopBarMetrics;
@property(copy) IBUISimulatedStatusBarMetrics *simulatedStatusBarMetrics;
- (struct CGSize)effectiveFreeformSize;
- (IBUISimulatedMetricsContainer *)effectiveSimulatedMetrics;
@end

