//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBViewDropTargetResolver.h>

@class IBOrderedRelationshipDragAndDropPolicy;

@interface IBUINavigationItemDropTargetResolver : IBViewDropTargetResolver
{
    IBOrderedRelationshipDragAndDropPolicy *_rightItemsPolicy;
    IBOrderedRelationshipDragAndDropPolicy *_leftItemsPolicy;
}

- (void).cxx_destruct;
- (struct CGRect)insertionPolicy:(id)arg1 confinementRectForRepresentedObject:(id)arg2;
- (BOOL)canAcceptDragInfo:(id)arg1;
- (id)editedView;
- (void)populatePolicies:(id)arg1;
- (id)editedNavigationItem;

@end

