//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTDaemonControlMobileDevice/XCTConfigurableDebugLogger-Protocol.h>

@protocol XCTRemoteHostDiagnosticReportsSynchronizing;

@protocol XCTTransportProvider <XCTConfigurableDebugLogger>
@property(readonly) id <XCTRemoteHostDiagnosticReportsSynchronizing> remoteHostDiagnosticReportsSynchronizer;
- (void)invalidate;
- (void)makeTransportWithCompletion:(void (^)(DTXTransport *, NSError *))arg1;
@end

