//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDESourceControlTaskOperation.h>

@interface GitOperation : IDESourceControlTaskOperation
{
}

- (void)addQuietFlagIfNeeded:(id)arg1 defaultFlag:(BOOL)arg2;
- (id)errorFromErrorMessage:(id)arg1;
- (id)defaultArguments;
- (id)launchPath;
- (id)initWithRequest:(id)arg1;

@end

