//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC12DVTAnalytics33ProcessorUsagePointAppStoreSource : SwiftObject
{
    // Error parsing type: , name: appIdentifier
    // Error parsing type: , name: listServiceClass
    // Error parsing type: , name: downloadServiceClass
}

@end

