//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DVTCrashLogBinaryImageParser : NSObject
{
    NSString *_identifier;
    double _priority;
}

@property(readonly) double priority; // @synthesize priority=_priority;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)parsedBinaryImageFromText:(id)arg1;
- (id)initWithParserIdentifier:(id)arg1 priority:(double)arg2;

@end

