//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface _SwiftNativeNSArrayBase : NSArray
{
    // Error parsing type: {RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> >="refCounts"{atomic<swift::RefCountBitsT<swift::RefCountIsInline> >="__a_"A{RefCountBitsT<swift::RefCountIsInline>}}}, name: refCounts
}

- (void)dealloc;
- (BOOL)retainWeakReference;
- (BOOL)allowsWeakReference;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;

@end

