//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs20_SwiftNativeNSString.h>

#import <swiftCore/_TtPs13_NSStringCore_-Protocol.h>

@interface _TtCs19_NSContiguousString : _TtCs20_SwiftNativeNSString <_TtPs13_NSStringCore_>
{
    // Error parsing type: , name: _guts
}

- (id)init;
- (id)copyWithZone:(void *)arg1;
- (const unsigned short *)_fastCharacterContents;
- (void)getCharacters:(unsigned short *)arg1 range:(CDStruct_912cb5d2)arg2;
- (unsigned short)characterAtIndex:(long long)arg1;
@property(nonatomic, readonly) long long length;
- (id)initWithCoder:(id)arg1;

@end

