//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol _TtPs9_NSNumber_
@property(nonatomic, readonly) const char *objCType;
@property(nonatomic, readonly) long long longLongValue;
@property(nonatomic, readonly) unsigned long long unsignedLongLongValue;
@property(nonatomic, readonly) float floatValue;
@property(nonatomic, readonly) double doubleValue;
@end

