//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderModel.h>

@class IDEIntentBuilderGroupItem, NSArray;

@interface IDEIntentBuilderModel (EditorAdditions)
+ (id)systemIntentsModel;
+ (id)keyPathsForValuesAffectingCanRemovedSelectedItem;
@property(readonly, nonatomic) NSArray *visibleGroups;
- (void)selectFirstItem;
@property(retain, nonatomic) IDEIntentBuilderGroupItem *selectedItem;
@property(readonly) BOOL canRemovedSelectedItem;
@end

