//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderIntentGroup.h>

#import <IDEIntentBuilderEditor/IDEIntentBuilderGroupEditable-Protocol.h>

@class NSString;

@interface IDEIntentBuilderIntentGroup (EditorAdditions) <IDEIntentBuilderGroupEditable>
- (id)imageName;
@property(readonly) BOOL canEditItems;
@property(readonly) BOOL canRenameItems;
@property(readonly, nonatomic, getter=isHiddenWhenEmpty) BOOL hiddenWhenEmpty;

// Remaining properties
@property(readonly) BOOL canRemoveItems;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

