//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderEnumValue.h>

@interface IDEIntentBuilderEnumValue (EditorAdditions)
+ (id)keyPathsForValuesAffectingRemovable;
+ (id)keyPathsForValuesAffectingEditable;
@property(readonly, getter=isDisplayNameEditable) BOOL displayNameEditable;
@property(readonly, getter=isRemovable) BOOL removable;
@property(readonly, getter=isEditable) BOOL editable;
@end

