//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderIntentParameter.h>

@interface IDEIntentBuilderIntentParameter (EditorAdditions)
+ (id)keyPathsForValuesAffectingTypeSupportsMultipleValues;
@property(readonly, getter=isEditable) BOOL editable;
@property(readonly, getter=isRemovable) BOOL removable;
@property(readonly, getter=isTypeEditable) BOOL typeEditable;
@property(readonly, nonatomic) BOOL typeSupportsMultipleValues;
@end

