//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtCC12IDEDocViewer18IDEDisplayTreeItemP33_34E36FE70FF0739630A6D6F06D22A32920CoderDeserialization : SwiftObject
{
}

- (id)entityWithURL:(id)arg1 isGroup:(BOOL)arg2 rawLanguage:(int)arg3 name:(id)arg4 kind:(long long)arg5;
- (id)groupMarkerWithParent:(id)arg1 name:(id)arg2;
- (id)collectionWithRawLanguageValue:(int)arg1;
- (id)rootIndexItem;

@end

