//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEDocViewer/_TtC12IDEDocViewer26IDEDisplayTreeIndexManager.h>

__attribute__((visibility("hidden")))
@interface _TtC12IDEDocViewer29IDEDNTDisplayTreeIndexManager : _TtC12IDEDocViewer26IDEDisplayTreeIndexManager
{
    // Error parsing type: , name: state
    // Error parsing type: , name: relinquishmentDelayedInvocation.storage
    // Error parsing type: , name: owners
    // Error parsing type: , name: contentCache
    // Error parsing type: , name: userStoragePath.storage
}

+ (void)setShared:(id)arg1;
+ (id)shared;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)indexFailedLoadingWithError:(id)arg1;
- (void)indexDidFinishLoading;
- (void)removeOwner:(id)arg1;
- (void)addOwner:(id)arg1;

@end

