//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC12IDEDocViewer29DocumentationExplorableSource : NSObject
{
    // Error parsing type: , name: rootIdentifier
    // Error parsing type: , name: synchronizationQueue.storage
    // Error parsing type: , name: index.storage
    // Error parsing type: , name: observer
}

+ (id)collectionWithIdentifier:(id)arg1;
+ (id)makeJumpBarController;
+ (id)URLForIdentifier:(id)arg1;
+ (id)identifierFrom:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

