//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEDocViewer/IDEDNTDisplayTreeIndexDelegate-Protocol.h>

@interface _TtC12IDEDocViewer26IDEDisplayTreeIndexManager : NSObject <IDEDNTDisplayTreeIndexDelegate>
{
}

- (id)init;
- (id)entityWithURL:(id)arg1 isGroup:(BOOL)arg2 rawLanguage:(int)arg3 name:(id)arg4 kind:(long long)arg5;
- (id)groupMarkerWithParent:(id)arg1 name:(id)arg2;
- (id)collectionWithRawLanguageValue:(int)arg1;
- (id)rootIndexItem;

@end

