//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEDocViewer/DVTStatefulObject-Protocol.h>

@class NSURL;
@protocol DVTExplorerNavigatorCommonCoreDelegate;

@protocol _TtP6DVTKit30DVTExplorerNavigatorCommonCore_ <DVTStatefulObject>
@property(retain, nonatomic) id <DVTExplorerNavigatorCommonCoreDelegate> delegate;
- (void)updateWithImplementationSpecifics:(id)arg1;
- (void)updateWithURL:(NSURL *)arg1;
- (void)revertState;
- (void)commitState;
@end

