//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol _TtP6DVTKit23DVTExplorableIdentifier_, _TtP6IDEKit30IDEExplorableJumpBarController_;

@protocol _TtP6IDEKit38IDEExplorableJumpBarControllerDelegate_
- (void)jumpBarController:(id <_TtP6IDEKit30IDEExplorableJumpBarController_>)arg1 userDidSelectIdentifier:(id <_TtP6DVTKit23DVTExplorableIdentifier_>)arg2;
@end

