//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEDocViewer/IDEDocJumpBarInterchange.h>

#import <IDEDocViewer/_TtP6IDEKit38IDEExplorableJumpBarControllerDelegate_-Protocol.h>

@class NSArray;
@protocol _TtP6IDEKit30IDEExplorableJumpBarController_;

@interface IDEDocJumpBarExplorablesInterchange : IDEDocJumpBarInterchange <_TtP6IDEKit38IDEExplorableJumpBarControllerDelegate_>
{
    id <_TtP6IDEKit30IDEExplorableJumpBarController_> _jumpBarController;
    NSArray *_pathControlBindingTokens;
}

@property(readonly, nonatomic) NSArray *pathControlBindingTokens; // @synthesize pathControlBindingTokens=_pathControlBindingTokens;
@property(readonly, nonatomic) id <_TtP6IDEKit30IDEExplorableJumpBarController_> jumpBarController; // @synthesize jumpBarController=_jumpBarController;
- (void).cxx_destruct;
- (BOOL)hasSelection;
- (id)_documentationURLForIdentifier:(id)arg1;
- (id)_explorableIdentifierForURLString:(id)arg1;
- (void)jumpBarController:(id)arg1 userDidSelectIdentifier:(id)arg2;
- (void)updateWithURLString:(id)arg1;
- (void)takeoverPathControl:(id)arg1;
- (void)primitiveInvalidate;
- (id)initWithDelegate:(id)arg1;

@end

