//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTExtension, DVTSourceCodeLanguage, NSString;

@interface IDEReferenceDocumentationInfo : NSObject
{
    int _sourceLanguage;
    NSString *_identifier;
    NSString *_title;
    NSString *_toolTip;
    id _backingExplorableIdentifier;
    DVTSourceCodeLanguage *_sourceCodeLanguage;
    DVTExtension *_navigatorExtension;
}

+ (id)infoWithIdentifier:(id)arg1;
+ (id)referenceDocumentationInfos;
@property(readonly, nonatomic) int sourceLanguage; // @synthesize sourceLanguage=_sourceLanguage;
@property(readonly, nonatomic) DVTExtension *navigatorExtension; // @synthesize navigatorExtension=_navigatorExtension;
@property(readonly, nonatomic) DVTSourceCodeLanguage *sourceCodeLanguage; // @synthesize sourceCodeLanguage=_sourceCodeLanguage;
@property(readonly, nonatomic) id backingExplorableIdentifier; // @synthesize backingExplorableIdentifier=_backingExplorableIdentifier;
@property(readonly, nonatomic) NSString *toolTip; // @synthesize toolTip=_toolTip;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)instantiateViewController;
- (id)referenceSpecificRootIdentifier;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCollection:(id)arg1 identifier:(id)arg2;
- (id)initWithExtension:(id)arg1;
@property(nonatomic, readonly) int language;

@end

