//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSEvent.h>

@interface NSEvent (IDEDocNSEventAdditions)
@property(readonly, nonatomic, getter=isCommandReturnKeyDown) BOOL commandReturnKeyDown;
@property(readonly, nonatomic, getter=isCommandRightArrowKeyDown) BOOL commandRightArrowKeyDown;
@property(readonly, nonatomic, getter=isCommandLeftArrowKeyDown) BOOL commandLeftArrowKeyDown;
@property(readonly, nonatomic, getter=isCommandPeriodKeyDown) BOOL commandPeriodKeyDown;
@property(readonly, nonatomic, getter=isCommandHomeKeyDown) BOOL commandHomeKeyDown;
@property(readonly, nonatomic, getter=isCommandBacktickKeyDown) BOOL commandBacktickKeyDown;
@end

