//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEProductsUI/_TtC13IDEProductsUI31ProcessorUsageLogViewController.h>

@interface _TtC13IDEProductsUI31ProcessorUsageLogViewController (IDEProductsUI3)
- (void)restoreScrollPosition;
- (void)saveScrollPositionWithLog:(id)arg1;
@end

