//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEProductsUI/NSObject-Protocol.h>

@class NSArray, NSAttributedString;

@protocol IDEArchiveStatusLogItemChild <NSObject>
@property(readonly) NSArray *children;
@property(readonly) NSAttributedString *attributedString;
@property(readonly) BOOL isNotice;
@property(readonly) BOOL isWarning;
@property(readonly) BOOL isError;
@end

