//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBXIBDocumentCompiler.h>

@interface IBCocoaXIBDocumentCompiler : IBXIBDocumentCompiler
{
}

+ (id)flatCompiledContentsOfDocument:(id)arg1 options:(id)arg2 error:(id *)arg3;
- (id)compileWithOptions:(id)arg1 error:(id *)arg2;
- (id)compiledKeyedObjectsDataWithOptions:(id)arg1 error:(id *)arg2;

@end

