//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBAbstractInterfaceBuilderPlatformToolManager.h>

@class IBPlatformToolDVTTaskExecutionContext;

@interface IBCocoaToolManager : IBAbstractInterfaceBuilderPlatformToolManager
{
    IBPlatformToolDVTTaskExecutionContext *_sharedExecutionContext;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)enumerateToolsWithBlock:(CDUnknownBlockType)arg1;
- (id)launchNewToolWithDescription:(id)arg1 error:(id *)arg2 forReason:(CDUnknownBlockType)arg3;
- (Class)toolProxyClass;
- (id)executionContextForDescription:(id)arg1 error:(id *)arg2;
- (id)contextForLaunchingToolWithDescription:(id)arg1 error:(id *)arg2;

@end

