//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaIntegration/IBNSControlEditor.h>

@interface IBMatrixEditor : IBNSControlEditor
{
}

+ (Class)ibDropTargetResolverClass;
- (BOOL)interceptEvent:(id)arg1;
- (id)acceptDragInfo:(id)arg1 context:(id)arg2;
- (id)matrix;

@end

