//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSString, NSTextField;

@interface IBNSViewPriorityPopoverViewController : NSViewController
{
    double _priority;
    NSString *_descriptiveText;
    NSTextField *_priorityTextField;
}

@property(retain, nonatomic) NSTextField *priorityTextField; // @synthesize priorityTextField=_priorityTextField;
@property(copy) NSString *descriptiveText; // @synthesize descriptiveText=_descriptiveText;
@property double priority; // @synthesize priority=_priority;
- (void).cxx_destruct;

@end

