//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet;

@interface IBNSGridCellXPlacementMenuItemValue : NSObject
{
    NSSet *_targets;
    long long _xPlacement;
}

+ (id)valueForTargets:(id)arg1 xPlacement:(long long)arg2;
@property long long xPlacement; // @synthesize xPlacement=_xPlacement;
@property(retain) NSSet *targets; // @synthesize targets=_targets;
- (void).cxx_destruct;

@end

