//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDateFormatter.h>

@interface NSDateFormatter (IBNSDateFormatterWidgetIntegration)
- (void)setIbShadowedFormatterBehavior:(long long)arg1;
- (long long)ibShadowedFormatterBehavior;
- (void)setIbShadowedDateFormat:(id)arg1;
- (id)ibShadowedDateFormat;
- (void)ibPopulateIssues:(id)arg1 forDocument:(id)arg2 withComputationContext:(id)arg3;
- (id)ibDefaultDataValueForTableView:(id)arg1;
- (id)ibLocalLocalizableStringsAttributeKeyPaths;
- (id)ibLocalAttributeKeyPaths;
@end

