//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSDictionaryController.h>

@class NSArray;

@interface NSDictionaryController (IBNSDictionaryControllerIntegration)
+ (id)ibDynamicShadowedKeyPathsToTypes;
- (BOOL)ibIsInspectorSliceApplicable:(id)arg1 forCategory:(id)arg2;
- (void)ibPopulateIssues:(id)arg1 forDocument:(id)arg2 withComputationContext:(id)arg3;
- (id)ibLocalAttributeKeyPaths;

// Remaining properties
@property(copy) NSArray *ibShadowedExcludedKeys; // @dynamic ibShadowedExcludedKeys;
@property(copy) NSArray *ibShadowedIncludedKeys; // @dynamic ibShadowedIncludedKeys;
@end

