//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTDeviceType, NSSet;

@interface _DVTDeviceTypeTreeNode : NSObject
{
    NSSet *_derivedDeviceTypes;
    _DVTDeviceTypeTreeNode *_parentNode;
    DVTDeviceType *_deviceType;
}

@property(readonly) NSSet *derivedDeviceTypes; // @synthesize derivedDeviceTypes=_derivedDeviceTypes;
@property(readonly) DVTDeviceType *deviceType; // @synthesize deviceType=_deviceType;
@property(readonly) __weak _DVTDeviceTypeTreeNode *parentNode; // @synthesize parentNode=_parentNode;
- (void).cxx_destruct;
- (void)setDerivedDeviceTypes:(id)arg1;
- (id)initWithParentNode:(id)arg1 deviceType:(id)arg2;

@end

