//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC13DVTFoundation24DVTIssueReportAttachment : SwiftObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: path
    // Error parsing type: , name: type
    // Error parsing type: , name: canBeAttachedAgain
    // Error parsing type: , name: uploaded
    // Error parsing type: , name: fileType
}

@end

