//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface DVTExtraXMLArchiveData : NSObject
{
    NSMutableArray *_mutableAttributes;
    NSMutableArray *_mutableElements;
}

@property(readonly) NSMutableArray *mutableElements; // @synthesize mutableElements=_mutableElements;
@property(readonly) NSMutableArray *mutableAttributes; // @synthesize mutableAttributes=_mutableAttributes;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

