//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface DVTFilterExpressionPredicateProducer : NSObject
{
    NSMutableDictionary *_identifierToAccessorMap;
}

- (void).cxx_destruct;
- (id)matcherForFilterExpression:(id)arg1 includingIdentifiers:(id)arg2;
- (id)matcherForFilterExpression:(id)arg1;
- (id)_predicateForExpression:(id)arg1;
- (id)_predicateForTextExpression:(id)arg1;
- (id)_predicateForNumericExpression:(id)arg1;
- (id)_predicateForCustomExpression:(id)arg1;
- (id)_predicateForCompoundFilterExpression:(id)arg1;
- (void)registerIdentifier:(id)arg1 withAccessorForNumericExpression:(CDUnknownBlockType)arg2;
- (void)registerIdentifier:(id)arg1 withAccessorForTextExpression:(CDUnknownBlockType)arg2;
- (void)registerIdentifier:(id)arg1 withAccessorForCustomExpression:(CDUnknownBlockType)arg2;
- (id)init;

@end

