//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S15IDESourceEditor010SourceCodeB0CN.h"

@interface _TtC29IDESourceCodeComparisonEditor26ComparisonSourceCodeEditor : _$S15IDESourceEditor010SourceCodeB0CN
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;

@end

