//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSColor;

__attribute__((visibility("hidden")))
@interface GPUBulletedViewBulletPainter : NSObject
{
    NSColor *_color;
}

+ (id)bulletImageWithPainter:(id)arg1;
+ (id)bulletImage;
- (void).cxx_destruct;
- (void)drawBullet:(id)arg1;
- (id)initWithColor:(id)arg1;

@end

