//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEIssue.h>

@class DYAnalyzerFinding;

__attribute__((visibility("hidden")))
@interface GPUIssue : IDEIssue
{
    DYAnalyzerFinding *_finding;
}

@property(nonatomic) __weak DYAnalyzerFinding *finding; // @synthesize finding=_finding;
- (void).cxx_destruct;

@end

