//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUTraceDebuggerUI/GPUCaptureLongClickPopUpButton.h>

__attribute__((visibility("hidden")))
@interface RightClickableButton : GPUCaptureLongClickPopUpButton
{
    SEL _leftButtonAction;
    SEL _rightButtonAction;
    id _target;
}

- (void).cxx_destruct;
- (void)rightMouseDown:(id)arg1;
- (void)setRightAction:(SEL)arg1;
- (void)setTarget:(id)arg1;
- (id)target;

@end

