//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DYGLTransformFeedbackBufferBinding : NSObject
{
    unsigned int _buffer;
    unsigned long long _offset;
    unsigned long long _size;
}

@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(nonatomic) unsigned int buffer; // @synthesize buffer=_buffer;
- (id)initWithProperties:(id)arg1;
- (id)init;

@end

