//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GKNoiseSource : NSObject
{
}

- (id)cloneModule;
- (void)setInputModule:(id)arg1 atIndex:(int)arg2;
- (id)inputModuleAtIndex:(int)arg1;
- (double)valueAt: /* Error: Ran out of types for this method. */;
- (int)requiredInputModuleCount;

@end

