//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSColor, NSString;

@interface DBGCanvasBackgroundColorChoice : NSObject
{
    NSString *_identifier;
    NSString *_name;
    NSColor *_color;
}

+ (id)standardColorChoiceWithIdentifier:(id)arg1;
+ (id)standardColorChoices;
+ (id)choiceWithIdentifier:(id)arg1 name:(id)arg2 color:(id)arg3;
@property(retain) NSColor *color; // @synthesize color=_color;
@property(retain) NSString *name; // @synthesize name=_name;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)debugDescription;

@end

