//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DebuggerUI/IDEDebuggingAddition-Protocol.h>

@protocol DBGKitDebuggingAddition <IDEDebuggingAddition>

@optional
@property(nonatomic) unsigned long long systemAppearanceTestingOverride;
@property(readonly, nonatomic) BOOL supportsSystemAppearanceTestingOverrides;
@property(nonatomic) BOOL showsResponsiveScrollingStatusOfAllViews;
@property(nonatomic) BOOL flashesDrawingOfAllViews;
@property(nonatomic) BOOL showsAlignmentRectanglesOfAllViews;
@property(nonatomic) BOOL showsFramesOfAllViews;
@end

