//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class IDESwiftErrorBreakpoint;

@interface IDESwiftErrorBreakpointEditorView : NSViewController
{
    IDESwiftErrorBreakpoint *_breakpoint;
}

@property(retain) IDESwiftErrorBreakpoint *breakpoint; // @synthesize breakpoint=_breakpoint;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithBreakpoint:(id)arg1;

@end

