//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DebuggerLLDB/NSObject-Protocol.h>

@protocol DBGSBAddress, DBGSBFileSpec;

@protocol DBGSBLineEntry <NSObject>
- (unsigned int)GetLine;
- (id <DBGSBAddress>)GetStartAddress;
- (id <DBGSBFileSpec>)GetFileSpec;
- (_Bool)IsValid;
- (id)initWithConnection:(id)arg1;
@end

