//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCBuildSupport/_TtP7XCBuild19XCBIndexingDelegate_-Protocol.h>

__attribute__((visibility("hidden")))
@interface _TtC17IDEXCBuildSupport36IDEXCBuildIndexingClientInfoProvider : NSObject <_TtP7XCBuild19XCBIndexingDelegate_>
{
    // Error parsing type: , name: provisioningManager
    // Error parsing type: , name: provisionable
    // Error parsing type: , name: runDestination
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)intentDefinitionGeneratedFilePathsWithInputPath:(id)arg1 outputDirPath:(id)arg2 languageToGenerate:(id)arg3 classPrefix:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)coreMLModelGeneratedFilePathsWithInputPath:(id)arg1 outputDirPath:(id)arg2 options:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)coreDataModelGeneratedFilePathsWithInputPath:(id)arg1 outputDirPath:(id)arg2 swiftVersion:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)provisioningTaskInputsWithTargetGUID:(id)arg1 provisioningSourceData:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithProvisioningManager:(id)arg1 provisionable:(id)arg2 runDestination:(id)arg3;

@end

