//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@interface _TtC18IDESourceControlUI38IDESourceControlAvatarFetcherOperation : NSOperation
{
    // Error parsing type: , name: email
    // Error parsing type: , name: size
    // Error parsing type: , name: context
    // Error parsing type: , name: completionHandler
    // Error parsing type: , name: operationInFlight
}

+ (id)keyPathsForValuesAffectingIsExecuting;
+ (id)keyPathsForValuesAffectingIsFinished;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (void)main;
- (void)cancel;
@property(nonatomic) BOOL operationInFlight; // @synthesize operationInFlight;

// Remaining properties
@property(nonatomic, readonly) BOOL executing;
@property(nonatomic, readonly) BOOL finished;

@end

