//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEKeyDrivenNavigableItem.h>

@interface _TtC18IDESourceControlUI28ForcedStructureNavigableItem : IDEKeyDrivenNavigableItem
{
}

- (id)init;
- (id)initWithRepresentedObject:(id)arg1;
- (BOOL)isLeaf;
@property(nonatomic, readonly) BOOL isDocumentNavigableItem;

// Remaining properties
@property(nonatomic, readonly) BOOL leaf;

@end

