//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface _TtC18IDESourceControlUI12JumpToButton : NSButton
{
    // Error parsing type: , name: hasDisplayableStatus
}

@property(nonatomic) BOOL hasDisplayableStatus; // @synthesize hasDisplayableStatus;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

