//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDESourceControlUI/DVTSourceControlAuthorImageProvider-Protocol.h>

@interface _TtC18IDESourceControlUI27IDESourceControlAvatarCache : NSObject <DVTSourceControlAuthorImageProvider>
{
    // Error parsing type: , name: _enabled
    // Error parsing type: , name: avatarCache
    // Error parsing type: , name: invalidAfterNumberOfDays
    // Error parsing type: , name: fetcher
    // Error parsing type: , name: updateQueue
    // Error parsing type: , name: inflightFetches
}

- (CDUnknownBlockType).cxx_destruct;
- (void)avatarForAuthor:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;
@property(nonatomic) BOOL enabled;

@end

