//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerKit/NSObject-Protocol.h>

@protocol DYPShaderDebuggerExecutionHistoryNode, DYPShaderDebuggerVariableSnapshotNode;

@protocol DYPShaderDebuggerVariableSnapshot <NSObject>
@property(nonatomic, readonly) unsigned long long eventId;
@property(nonatomic, readonly) id <DYPShaderDebuggerVariableSnapshotNode> rootNode;
@property(nonatomic, readonly) unsigned long long addressSpace;
@property(nonatomic, readonly) id <DYPShaderDebuggerExecutionHistoryNode> node;
@end

