//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerKit/GPUBufferViewerAdaptorDataSourceProvider.h>

@interface GPUBufferViewerPostVertexDataSourceProvider : GPUBufferViewerAdaptorDataSourceProvider
{
}

- (id)dataSourceFromSource:(id)arg1 error:(id *)arg2;
- (id)dataSourceWithType:(unsigned long long)arg1 rows:(unsigned long long)arg2 components:(unsigned long long)arg3 columns:(unsigned long long)arg4 error:(id *)arg5;
- (id)dataSourceForLayout:(id)arg1;

@end

