//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DTGraphKit/DTTimelineDecoratedPlane.h>

@interface GPUTimelineDecoratedPlane : DTTimelineDecoratedPlane
{
    unsigned long long _sortingIndex;
}

@property(nonatomic) unsigned long long sortingIndex; // @synthesize sortingIndex=_sortingIndex;
- (id)_unselectedTextColor;
- (id)_selectedTextColor;
- (BOOL)_wantsBottomBorderLayerWhenInGroupPlane;
- (long long)compare:(id)arg1;

@end

