//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, NSXMLDocument;

@interface LOCIBXMLParser : NSObject
{
    NSURL *_ontologyURL;
    NSXMLDocument *_xml;
    NSURL *_documentURL;
    NSURL *_ibFileURL;
}

@property(retain, nonatomic) NSURL *ibFileURL; // @synthesize ibFileURL=_ibFileURL;
@property(retain, nonatomic) NSURL *documentURL; // @synthesize documentURL=_documentURL;
@property(retain, nonatomic) NSXMLDocument *xml; // @synthesize xml=_xml;
@property(retain, nonatomic) NSURL *ontologyURL; // @synthesize ontologyURL=_ontologyURL;
- (void).cxx_destruct;
- (id)ibElementsForNode:(id)arg1 definitions:(id)arg2 restype:(id)arg3;
- (id)parseWithError:(id *)arg1;
- (id)loadDocumentWithError:(id *)arg1;
- (id)initWithOntology:(id)arg1 document:(id)arg2;

@end

