//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEModelFoundation/XDUMLMultiplicityElement-Protocol.h>
#import <IDEModelFoundation/XDUMLNamedElement-Protocol.h>

@protocol XDUMLType;

@protocol XDUMLTypedElement <XDUMLNamedElement, XDUMLMultiplicityElement>
- (void)setType:(id <XDUMLType>)arg1;
- (id <XDUMLType>)type;
@end

