//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEIndexGeniusResultsFinder.h>

@interface SKCustomClassGeniusResultsFinder : IDEIndexGeniusResultsFinder
{
}

+ (Class)editorDocumentClass;
- (id)_packagedGeniusResultsFromLocations:(id)arg1;
- (id)_geniusLocationsForCustomClassName:(id)arg1 inIndex:(id)arg2;
- (BOOL)_getUpdateGeniusResultsPhaseOneBlock:(CDUnknownBlockType *)arg1 phaseTwoBlock:(CDUnknownBlockType *)arg2 phaseThreeBlock:(CDUnknownBlockType *)arg3;
- (id)geniusCategoryIdentifier;

@end

