//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDESpriteKitParticleEditor/SKSceneSelecting-Protocol.h>

@protocol SKSceneManipulating_Impl <SKSceneSelecting>
@property(readonly, nonatomic) unsigned long long manipulationSupport;

@optional
@property(nonatomic) struct CGPoint anchorPoint;
@property(nonatomic) double zRotation;
@property(nonatomic) double yScale;
@property(nonatomic) double xScale;
@property(nonatomic) struct CGPoint position;
@end

