//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

__attribute__((visibility("hidden")))
@interface _TtC10Foundation12_NSSwiftData : NSData
{
    // Error parsing type: , name: _backing
    // Error parsing type: , name: _range
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithContentsOfMappedFile:(id)arg1;
- (id)initWithBase64EncodedData:(id)arg1 options:(unsigned long long)arg2;
- (id)initWithBase64EncodedString:(id)arg1 options:(unsigned long long)arg2;
- (id)initWithData:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
- (id)initWithContentsOfFile:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
- (id)initWithBytesNoCopy:(void *)arg1 length:(long long)arg2 deallocator:(CDUnknownBlockType)arg3;
- (id)initWithBytesNoCopy:(void *)arg1 length:(long long)arg2 freeWhenDone:(BOOL)arg3;
- (id)initWithBytesNoCopy:(void *)arg1 length:(long long)arg2;
- (id)initWithBytes:(void *)arg1 length:(long long)arg2;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (BOOL)_providesConcreteBacking;
- (BOOL)_isCompact;
- (id)mutableCopyWithZone:(void *)arg1;
- (id)copyWithZone:(void *)arg1;
@property(nonatomic, readonly) void *bytes;
@property(nonatomic, readonly) long long length;

@end

