//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftFoundation/_TtC10FoundationP33_12768CA107A31EF2DCE034FD75B541C912_JSONEncoder.h>

@interface _TtC10FoundationP33_12768CA107A31EF2DCE034FD75B541C923_JSONReferencingEncoder : _TtC10FoundationP33_12768CA107A31EF2DCE034FD75B541C912_JSONEncoder
{
    // Error parsing type: , name: encoder
    // Error parsing type: , name: reference
}

@end

