//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC10FoundationP33_6DA0945A07226B3278459E9368612FF426_KVOKeyPathBridgeMachinery : NSObject
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

