//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7DVTJRPC22JRPCFileHandleEndpoint : SwiftObject
{
    // Error parsing type: , name: requestHandlerMap
    // Error parsing type: , name: responseHandlerMap
    // Error parsing type: , name: messageStream
    // Error parsing type: , name: fileHandleForSending
    // Error parsing type: , name: fileHandleForReceiving
}

@end

