//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7DVTJRPC17JRPCMessageStream : SwiftObject
{
    // Error parsing type: , name: callback
    // Error parsing type: , name: availableData
    // Error parsing type: , name: state
    // Error parsing type: , name: processQueue
    // Error parsing type: , name: callbackQueue
}

@end

