//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC26IDEPegasusPlaygroundEditorP33_34E08EDDF25C012D00A480F8D84AF2A834LineNumberHidingAttributesProvider : SwiftObject
{
    // Error parsing type: , name: hiddenLineNumber
}

@end

