//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC26IDEPegasusPlaygroundEditorP33_304ABAEE8C8C56C228038B23F9F4185F25PlaygroundExecutionRanges : SwiftObject
{
    // Error parsing type: , name: alreadyExecutedRange
    // Error parsing type: , name: currentlyExecutingRange
    // Error parsing type: , name: pendingExecutionRange
}

@end

