//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusPlaygroundEditor/NSObject-Protocol.h>

@class DVTFilePath, NSString;

@protocol IDEPlaygroundAppBundle <NSObject>
- (BOOL)cleanUpAppBundle:(id *)arg1;
@property(nonatomic, readonly) DVTFilePath *containerPath;
@property(nonatomic, readonly) NSString *bundleIdentifier;
@property(nonatomic, readonly) NSString *executableSubpath;
@property(nonatomic, readonly) DVTFilePath *appBundlePath;
@end

