//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Xcode3Core/IDEProvisionable-Protocol.h>

@class NSString;
@protocol IDEProvisioningBasicProfile, IDEProvisioningBasicTeam;

@protocol IDEMutableProvisionable <IDEProvisionable>
- (void)setSigningCertificateIdentifier:(NSString *)arg1 forConfigurationNamed:(NSString *)arg2;
- (void)setProvisioningProfile:(id <IDEProvisioningBasicProfile>)arg1 forConfigurationNamed:(NSString *)arg2;
- (void)setTeam:(id <IDEProvisioningBasicTeam>)arg1 forConfigurationNamed:(NSString *)arg2;
- (void)setProvisioningStyle:(long long)arg1 forConfigurationNamed:(NSString *)arg2;
@end

