//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7XCBuild25XCBBuildServiceConnection : SwiftObject
{
    // Error parsing type: , name: _isSuspended
    // Error parsing type: , name: _isClosed
    // Error parsing type: , name: _wasCreated
    // Error parsing type: , name: _task
    // Error parsing type: , name: _queue
    // Error parsing type: , name: _stateQueue
    // Error parsing type: , name: _stdinWriter
    // Error parsing type: , name: _stdoutReader
    // Error parsing type: , name: _bufferedData
    // Error parsing type: , name: _nextChannelID
    // Error parsing type: , name: _channels
    // Error parsing type: , name: _channelsHaveBeenCleared
    // Error parsing type: , name: _channelLock
}

@end

