//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC7XCBuild26IncrementalPIFLookupResult : NSObject
{
    // Error parsing type: , name: object
    // Error parsing type: , name: diagnostics
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithObject:(id)arg1 diagnostics:(id)arg2;
@property(nonatomic, readonly) NSString *diagnostics; // @synthesize diagnostics;
@property(nonatomic, readonly) id object; // @synthesize object;

@end

