//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7XCBuild16XCBXBSParameters : SwiftObject
{
    // Error parsing type: , name: project
    // Error parsing type: , name: update
    // Error parsing type: , name: sourceVersion
    // Error parsing type: , name: buildNumber
    // Error parsing type: , name: buildRecord
}

@end

