//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC7XCBuild22XCBBuildServiceConsole : NSObject
{
    // Error parsing type: , name: service
    // Error parsing type: , name: inferiorProductsPath
    // Error parsing type: , name: sessions
    // Error parsing type: , name: activeSession
    // Error parsing type: , name: commandRegistry
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

