//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LoggingSupportHost/_OSLogPredicateMapper.h>

__attribute__((visibility("hidden")))
@interface _OSLogLegacyPredicateMapper : _OSLogPredicateMapper
{
}

- (void)mapLeftExpression:(id *)arg1 andRightExpression:(id *)arg2;
- (id)validKeyPaths;

@end

