//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTInstrumentsFoundation/DTOSLogLoaderTicket.h>

@class OSLogEventStreamPosition;

__attribute__((visibility("hidden")))
@interface DTOSLogLoaderFetchTicket : DTOSLogLoaderTicket
{
    double _windowInSeconds;
    OSLogEventStreamPosition *_currentPosition;
}

@property(retain, nonatomic) OSLogEventStreamPosition *currentPosition; // @synthesize currentPosition=_currentPosition;
@property(nonatomic) double windowInSeconds; // @synthesize windowInSeconds=_windowInSeconds;
- (void).cxx_destruct;
- (void)prepareAgent:(id)arg1 loader:(id)arg2;
- (void)holdAgent:(id)arg1 loader:(id)arg2;

@end

