//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Xcode3UI/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString;
@protocol Xcode3SourceListItemEditing;

@protocol Xcode3SourceListItemEditing <NSObject>
+ (id <Xcode3SourceListItemEditing>)deserializedSourceListItem:(NSDictionary *)arg1;
+ (NSString *)pasteboardDataType;
- (NSDictionary *)serializedSourceListItem;
- (NSArray *)supportedSourceListItemEditorClasses;
@end

