//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface Xcode3ImagePopUpButtonCell : NSButtonCell
{
}

- (void)performAction:(id)arg1;
- (SEL)action;
- (id)target;
- (void)awakeFromNib;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (void)_commonInit;

@end

