//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Xcode3UI/Xcode3CustomUpgradeTask.h>

@interface Xcode3UpdateSwiftTask : Xcode3CustomUpgradeTask
{
}

+ (id)analyzeInContext:(id)arg1;
+ (id)_supportedSwiftVersionsForTargetContext:(id)arg1;
- (id)handlerForTask;

@end

