//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtCE6AppKitVSo17NSAnimationEffectP33_9E6F1C1DB126EBCC5B18B8BAC8A387CC26_CompletionHandlerDelegate : NSObject
{
    // Error parsing type: , name: completionHandler
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)animationEffectDidEnd:(void *)arg1;

@end

