//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEIndexGeniusResultsFinder.h>

@interface IDESourceCodeIndexGeniusResultsFinder : IDEIndexGeniusResultsFinder
{
}

+ (Class)editorDocumentClass;
+ (id)_classSourceLandmarkItemForTopSourceLandmarkItem:(id)arg1 location:(unsigned long long)arg2;
+ (id)_classSourceLandmarkItemForSourceLandmarkItem:(id)arg1;
+ (void)initialize;
- (BOOL)_getUpdateGeniusResultsPhaseOneBlock:(CDUnknownBlockType *)arg1 phaseTwoBlock:(CDUnknownBlockType *)arg2 phaseThreeBlock:(CDUnknownBlockType *)arg3;

@end

