//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC24DVTDeviceControlServices20JRPCFileHandleServer : SwiftObject
{
    // Error parsing type: , name: fileHandleForReading
    // Error parsing type: , name: fileHandleForWriting
    // Error parsing type: , name: endpoint
    // Error parsing type: , name: serviceHost
}

@end

