//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class DVTReplacementView, NSArray, SKESceneDocument;

@interface SKEPostProcessEditor : IDEViewController
{
    DVTReplacementView *_editorReplacementView;
    NSArray *_content;
    SKESceneDocument *_document;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SKESceneDocument *document;
- (void)setDocument:(id)arg1;
@property(copy, nonatomic) NSArray *content;
- (void)loadView;
- (void)primitiveInvalidate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

