//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S7XCBuild22XCBBuildServiceConsoleCN.h"

@interface _TtC19IDEXCBuildSupportUI25IDEXCBBuildServiceConsole : _$S7XCBuild22XCBBuildServiceConsoleCN
{
    // Error parsing type: , name: selectedBuildServiceSession
}

- (CDUnknownBlockType).cxx_destruct;

@end

