//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSTextField, NSTextView;

__attribute__((visibility("hidden")))
@interface IDEXCBuildConsoleController : NSWindowController
{
    // Error parsing type: , name: _buildServiceConsole.storage
    // Error parsing type: , name: logTextView
    // Error parsing type: , name: inputTextField
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)inputTextFieldDidChange:(id)arg1;
- (void)loadXCBuildConsole:(id)arg1;
- (id)init;
@property(nonatomic, retain) NSTextField *inputTextField; // @synthesize inputTextField;
@property(nonatomic, retain) NSTextView *logTextView; // @synthesize logTextView;

@end

