//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTDaemonControl/NSObject-Protocol.h>

@class XCTProtocolVersion;
@protocol XCTestManager_DaemonConnectionInterface;

@protocol XCTDaemonProxyProviding <NSObject>
@property(readonly, copy) XCTProtocolVersion *protocolVersion;
@property(readonly) id <XCTestManager_DaemonConnectionInterface> proxy;
@end

