//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DebuggerFoundation/DBGComputedSnapshotPropertyProvider-Protocol.h>
#import <DebuggerFoundation/DBGDataSourceConnection-Protocol.h>
#import <DebuggerFoundation/DVTInvalidation-Protocol.h>

@class DVTStackBacktrace, IDEDebugSession, NSString;
@protocol DBGDataSourceConnectionDelegate;

@interface DBGDataSourceConnectionLibViewDebugger : NSObject <DVTInvalidation, DBGDataSourceConnection, DBGComputedSnapshotPropertyProvider>
{
    IDEDebugSession *_debugSession;
    id <DBGDataSourceConnectionDelegate> _delegate;
    double _debugHierarchyVersion;
    long long _debugHierarchyFoundationLoadedState;
    long long _liblViewDebuggerSupportDylibLoadedState;
}

+ (Class)matchingDataCoordinatorClass;
+ (Class)dataSourceConnectionLibViewDebuggerHelperClass;
+ (BOOL)shouldInstantiateInLaunchSession:(id)arg1;
+ (void)initialize;
@property long long liblViewDebuggerSupportDylibLoadedState; // @synthesize liblViewDebuggerSupportDylibLoadedState=_liblViewDebuggerSupportDylibLoadedState;
@property long long debugHierarchyFoundationLoadedState; // @synthesize debugHierarchyFoundationLoadedState=_debugHierarchyFoundationLoadedState;
@property double debugHierarchyVersion; // @synthesize debugHierarchyVersion=_debugHierarchyVersion;
@property __weak id <DBGDataSourceConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) IDEDebugSession *debugSession; // @synthesize debugSession=_debugSession;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)computedPropertyWithName:(id)arg1 onNode:(id)arg2;
- (id)_targetConfigurationFetchExpression;
- (void)_invokeCompletionHandlerForFailedConfigurationRetrieval:(CDUnknownBlockType)arg1 withErrorMessage:(id)arg2;
- (void)_invokeCompletionHandlerForCurrentConfiguration:(CDUnknownBlockType)arg1;
- (void)retrieveDebugHierarchyConfiguration:(CDUnknownBlockType)arg1;
- (void)performRequest:(id)arg1;
- (void)_executeLLDBExpression:(id)arg1 forRequest:(id)arg2 onPotentialThread:(id)arg3 iteration:(unsigned long long)arg4;
- (void)executeLLDBExpression:(id)arg1 forRequest:(id)arg2;
- (id)initWithDebugSession:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

