//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DebuggerFoundation/DBGSKNodeSurface.h>

@interface DBGSKScene : DBGSKNodeSurface
{
    long long _scaleMode;
    struct CGSize _size;
}

@property struct CGSize size; // @synthesize size=_size;
@property long long scaleMode; // @synthesize scaleMode=_scaleMode;
- (id)cameraNode;
- (void)_updatePropertiesWithSnapshotNode:(id)arg1 forRequest:(id)arg2;

@end

