//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEFileReference.h>

@interface _IDEResultBundleChildFileReference : IDEFileReference
{
    BOOL _editable;
}

- (id)resolvedFilePath;
- (id)navigableItem_conformanceString;
- (BOOL)_filePathExists;
- (BOOL)isEditable;
- (id)_initWithPath:(id)arg1 fileDataTypeIdentifier:(id)arg2;

@end

