//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/_TtP13IDEFoundation22IDETestingOutputStream_-Protocol.h>

@interface _TtC13IDEFoundation27IDETestingBlockOutputStream : NSObject <_TtP13IDEFoundation22IDETestingOutputStream_>
{
    // Error parsing type: , name: writeHandler
    // Error parsing type: , name: finishHandler
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)finish;
@property(nonatomic, copy) CDUnknownBlockType finishHandler; // @synthesize finishHandler;
- (void)writeString:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType writeStringHandler; // @synthesize writeStringHandler=writeHandler;

@end

