//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S16DVTDocumentation0A7ManagerCN.h"

@interface _TtC13IDEFoundation23IDEDocumentationManager : _$S16DVTDocumentation0A7ManagerCN
{
}

+ (id)normalizeSearchQuery:(id)arg1 preservingCase:(BOOL)arg2;
- (id)performSearch:(id)arg1 in:(int)arg2 limit:(long long)arg3 qualityOfService:(long long)arg4 completionBlock:(CDUnknownBlockType)arg5;

@end

