//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC13IDEFoundation25NotarizationTicketContent : NSObject
{
    // Error parsing type: , name: path
    // Error parsing type: , name: arch
    // Error parsing type: , name: digestAlgorithm
    // Error parsing type: , name: cdhash
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSString *cdhash; // @synthesize cdhash;
@property(nonatomic, readonly) NSString *digestAlgorithm; // @synthesize digestAlgorithm;
@property(nonatomic, readonly) NSString *arch; // @synthesize arch;
@property(nonatomic, readonly) NSString *path; // @synthesize path;

@end

