//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation32IDETestingFileHandleOutputStream.h>

#import <IDEFoundation/_TtP13IDEFoundation22IDETestingOutputStream_-Protocol.h>

@interface _TtC13IDEFoundation32IDETestingFileHandleOutputStream (IDEFoundation) <_TtP13IDEFoundation22IDETestingOutputStream_>
- (void)finish;
- (void)writeString:(id)arg1;
@end

