//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation23IDETestDaemonController.h>

#import <IDEFoundation/XCTDaemonControlSessionDelegate-Protocol.h>

@interface _TtC13IDEFoundation23IDETestDaemonController (IDEFoundation1) <XCTDaemonControlSessionDelegate>
- (void)daemonControlSession:(id)arg1 didReportSelfDiagnosisIssue:(id)arg2 description:(id)arg3;
- (void)daemonControlSession:(id)arg1 didReceiveDebugLogMessage:(id)arg2;
- (void)daemonControlSession:(id)arg1 didReceiveCrashReportData:(id)arg2 fileName:(id)arg3;
- (void)daemonSessionDidDisconnect:(id)arg1;
@end

