//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation34IDESourceControlHostAuthentication.h>

@interface _TtC13IDEFoundation39IDESourceControlHostBasicAuthentication : _TtC13IDEFoundation34IDESourceControlHostAuthentication
{
    // Error parsing type: , name: basicAuthentication
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithUsername:(id)arg1 password:(id)arg2;

@end

