//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTInvalidation_NSObject.h>

@class NSString;

@interface _TtC13IDEFoundation28IDEStructureEditingProcedure : DVTInvalidation_NSObject
{
    // Error parsing type: , name: topLevelOperation
    // Error parsing type: , name: _mainThreadTimeSlicingQueue
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) double progress;
@property(nonatomic, readonly) NSString *title;
- (void)primitiveInvalidate;
- (id)init;

@end

