//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC13IDEFoundation27IDETestingMultiOutputStream : NSObject
{
    // Error parsing type: , name: outputStreams
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithOutputStreams:(id)arg1;

@end

