//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSNumber, NSString, NSURL;

@interface _TtC13IDEFoundation17NotarizationIssue : NSObject
{
    // Error parsing type: , name: severity
    // Error parsing type: , name: path
    // Error parsing type: , name: message
    // Error parsing type: , name: docUrl
    // Error parsing type: , name: internalCode
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) NSError *errorRepresentation;
@property(nonatomic, readonly) long long distributionIssueSeverity;
@property(nonatomic, readonly) NSNumber *code;
@property(nonatomic, readonly) NSURL *docUrl; // @synthesize docUrl;
@property(nonatomic, readonly) NSString *message; // @synthesize message;
@property(nonatomic, readonly) NSString *path; // @synthesize path;
@property(nonatomic, readonly) NSString *severity; // @synthesize severity;

@end

