//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSData, NSString;
@protocol IDETestDaemonController;

@protocol _TtP13IDEFoundation31IDETestDaemonControllerObserver_

@optional
- (void)testDaemonController:(id <IDETestDaemonController>)arg1 receivedCrashReportWithData:(NSData *)arg2 bundleID:(NSString *)arg3 binaryPath:(NSString *)arg4 pid:(int)arg5 crashingSymbol:(NSString *)arg6;
- (void)testDaemonControllerDidDisconnect:(id <IDETestDaemonController>)arg1;
@end

