//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/DVTAnalyticsLogProtocol-Protocol.h>

@class DVTCrashLogThread, NSArray;

@protocol DVTAnalyticsLogProtocol_IDEAdditions <DVTAnalyticsLogProtocol>
@property(readonly) DVTCrashLogThread *crashingThread;
- (void)demangleUsingToolchains:(NSArray *)arg1 callback:(void (^)(id <DVTAnalyticsLogProtocol_IDEAdditions>, NSError *))arg2;
@end

