//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTAnalytics/DVTCrashLog.h>

#import <IDEFoundation/DVTAnalyticsLogProtocol_IDEAdditions-Protocol.h>

@class DVTCrashLogThread, NSString;

@interface DVTCrashLog (IDEAdditions) <DVTAnalyticsLogProtocol_IDEAdditions>
- (id)_recomputedRawDataUsingDemangledNames:(id)arg1 error:(id *)arg2;
- (void)demangleUsingToolchains:(id)arg1 callback:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly) NSString *appName;
@property(readonly) NSString *blameThreadDescription;
@property(readonly) NSString *build;
@property(readonly) DVTCrashLogThread *crashingThread;
@property(readonly) NSString *hardwareModelDescription;
@property(readonly) NSString *identifier;
@property(readonly) BOOL isFullySymbolicated;
@property(readonly) BOOL isLocallySymbolicatedCachePath;
@property(readonly) NSString *longUserDescription;
@property(readonly) NSString *osBuild;
@property(readonly) NSString *osVersion;
@property(readonly) NSString *version;
@end

