//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTOperation.h>

#import <IDEFoundation/DVTProgressReporting-Protocol.h>

@class DVTFilePath, IDEActivityLogSection, IDESchemeActionResult, NSArray, NSOperationQueue, NSString;

@interface IDECoverageReportGenerationOperation : DVTOperation <DVTProgressReporting>
{
    NSString *_logIdentifier;
    NSArray *_buildableInfos;
    DVTFilePath *_coverageReportDestinationPath;
    DVTFilePath *_coverageArchiveDestinationPath;
    DVTFilePath *_profileFilePath;
    IDEActivityLogSection *_testLog;
    IDESchemeActionResult *_schemeActionResult;
    long long _progress;
    NSOperationQueue *_workQueue;
    NSOperationQueue *_ioQueue;
}

+ (id)coverageErrorsTestLogSectionDomainType;
+ (id)logAspect;
+ (id)coverageBuildableInfosForScheme:(id)arg1 schemeCommand:(id)arg2 buildParameters:(id)arg3;
@property(retain, nonatomic) NSOperationQueue *ioQueue; // @synthesize ioQueue=_ioQueue;
@property(retain, nonatomic) NSOperationQueue *workQueue; // @synthesize workQueue=_workQueue;
@property long long progress; // @synthesize progress=_progress;
@property(nonatomic) __weak IDESchemeActionResult *schemeActionResult; // @synthesize schemeActionResult=_schemeActionResult;
@property(retain) IDEActivityLogSection *testLog; // @synthesize testLog=_testLog;
@property(retain) DVTFilePath *profileFilePath; // @synthesize profileFilePath=_profileFilePath;
@property(retain) DVTFilePath *coverageArchiveDestinationPath; // @synthesize coverageArchiveDestinationPath=_coverageArchiveDestinationPath;
@property(retain) DVTFilePath *coverageReportDestinationPath; // @synthesize coverageReportDestinationPath=_coverageReportDestinationPath;
@property(retain, nonatomic) NSArray *buildableInfos; // @synthesize buildableInfos=_buildableInfos;
@property(readonly, copy) NSString *logIdentifier; // @synthesize logIdentifier=_logIdentifier;
- (void).cxx_destruct;
- (void)cancel;
- (void)main;
- (id)initWithBuildableInfos:(id)arg1 coverageReportDestinationPath:(id)arg2 coverageArchiveDestinationPath:(id)arg3 schemeActionResult:(id)arg4 profileFilePath:(id)arg5;
- (void)appendErrorsToTestLog:(id)arg1;
- (BOOL)writeCoverageReportToDisk:(id)arg1 error:(id *)arg2;
- (id)buildersForBuildableInfos:(id)arg1 errors:(id)arg2;
- (id)generateTargetsForBuildableInfos:(id)arg1 updatingArchive:(id)arg2;
- (id)generateCoverageForFilesUsingBuilders:(id)arg1 updatingArchive:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

