//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEDistributionMethod.h>

@class DVTPlatform;

@interface IDEDistributionMethodAppleSigning : IDEDistributionMethod
{
}

- (id)orderedDistributionStepClassNamesForTask:(long long)arg1 destination:(long long)arg2;
- (id)orderedDistributionStepClassNamesForDestination:(long long)arg1;
- (BOOL)requiresAppStoreConfigurationForDestination:(long long)arg1;
@property(readonly) DVTPlatform *supportedPlatform;
- (id)exportStepName;

@end

