//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTPlatform, NSError;

@interface IDEDistributionItemPlatform : NSObject
{
    DVTPlatform *_platform;
    NSError *_platformError;
}

+ (id)distributionItemPlatformWithPlatform:(id)arg1 platformError:(id)arg2;
@property(readonly) NSError *platformError; // @synthesize platformError=_platformError;
@property(readonly) DVTPlatform *platform; // @synthesize platform=_platform;
- (void).cxx_destruct;

@end

