//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface IDEIndexRingBuffer : NSObject
{
    NSMutableArray *_buffer;
    long long _first;
    long long _capacity;
}

- (void).cxx_destruct;
@property(readonly) long long count;
- (id)removeAll;
- (void)addObject:(id)arg1;
- (id)init;
- (id)initWithCapacity:(long long)arg1;

@end

