//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEActivityLogRecord.h>

@class DVTFileDataType;
@protocol IDELogStoreManageable;

@interface IDEInMemoryActivityLogRecord : IDEActivityLogRecord
{
    id <IDELogStoreManageable> _fullLog;
    DVTFileDataType *_documentType;
}

+ (id)keyPathsForValuesAffectingTimeStoppedRecording;
+ (id)keyPathsForValuesAffectingIsRecording;
- (id)logStoreManageable;
- (void).cxx_destruct;
- (id)description;
- (double)timeStoppedRecording;
- (id)buildMetricsReportFilePath;
- (BOOL)collectMetrics;
- (id)highLevelStatus;
- (id)signature;
- (id)documentType;
- (double)timeStartedRecording;
- (id)title;
- (id)auxiliaryLogUniqueIdentifier;
- (id)uniqueIdentifier;
- (id)domainType;
- (BOOL)isRecording;
- (id)fullLogIfInMemory;
- (id)fullLogStoreManageableWithError:(id *)arg1;
- (id)fullLogWithError:(id *)arg1;
- (id)initWithLog:(id)arg1 entityIdentifier:(id)arg2;

@end

