//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/NSObject-Protocol.h>

@class DVTFilePath, IDEActivityLogSection, IDETypeIdentifier, NSString;
@protocol IDELogStoreManageable;

@protocol IDELogStoreManageable <NSObject>
+ (id <IDELogStoreManageable>)makeInstanceWithContentsOfFile:(NSString *)arg1 error:(id *)arg2;
@property(readonly, copy) NSString *overrideMetricsPath;
@property(readonly) BOOL collectMetrics;
@property(readonly, copy) DVTFilePath *testableSummariesPlistFilePath;
@property(readonly, copy) DVTFilePath *coverageArchiveFilePath;
@property(readonly, copy) DVTFilePath *coverageReportFilePath;
@property(readonly) BOOL hasCoverageData;
@property(copy) DVTFilePath *filePath;
@property(readonly, copy) NSString *defaultFileName;
@property(readonly) IDEActivityLogSection *auxiliaryLogSection;
@property(readonly) IDEActivityLogSection *logSection;
@property(readonly) unsigned long long totalNumberOfAnalyzerResults;
@property(readonly) unsigned long long totalNumberOfWarnings;
@property(readonly) unsigned long long totalNumberOfErrors;
@property(readonly) unsigned long long totalNumberOfTestFailures;
@property(readonly) BOOL isRecording;
@property(readonly) double timeStoppedRecording;
@property(readonly) double timeStartedRecording;
@property(readonly) IDETypeIdentifier *domainType;
@property(readonly, copy) NSString *title;
@property(readonly, copy) NSString *signature;
@property(readonly, copy) NSString *uniqueIdentifier;
- (void)addCompletionBlock:(void (^)(void))arg1;
- (BOOL)writeToFile:(NSString *)arg1 error:(id *)arg2;
@end

