//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEActivityLogRecord.h>

@class DVTFileDataType, DVTObservingToken, IDETypeIdentifier, NSDictionary, NSString;
@protocol IDELogStoreManageable, IDEOnDiskActivityLogRecordManaging;

@interface IDEOnDiskActivityLogRecord : IDEActivityLogRecord
{
    id <IDELogStoreManageable> _logStoreManageable;
    double _timeStoppedRecording;
    NSString *_uniqueIdentifier;
    NSString *_auxiliaryLogUniqueIdentifier;
    double _timeStartedRecording;
    DVTFileDataType *_documentType;
    IDETypeIdentifier *_domainType;
    NSString *_title;
    NSString *_signature;
    NSString *_highLevelStatus;
    id <IDEOnDiskActivityLogRecordManaging> _logRecordManager;
    NSString *_logFileName;
    NSString *_logClassName;
    DVTObservingToken *_recorderLogObservingToken;
}

+ (id)keyPathsForValuesAffectingIsRecording;
+ (id)entityIdentifierFromDictionary:(id)arg1;
@property(retain) DVTObservingToken *recorderLogObservingToken; // @synthesize recorderLogObservingToken=_recorderLogObservingToken;
@property(readonly, copy) NSString *logClassName; // @synthesize logClassName=_logClassName;
@property(readonly, copy) NSString *logFileName; // @synthesize logFileName=_logFileName;
@property(readonly) __weak id <IDEOnDiskActivityLogRecordManaging> logRecordManager; // @synthesize logRecordManager=_logRecordManager;
- (id)highLevelStatus;
- (id)signature;
- (id)title;
- (id)domainType;
- (id)documentType;
- (double)timeStartedRecording;
- (id)auxiliaryLogUniqueIdentifier;
- (id)uniqueIdentifier;
- (double)timeStoppedRecording;
@property(readonly) id <IDELogStoreManageable> logStoreManageable; // @synthesize logStoreManageable=_logStoreManageable;
- (void).cxx_destruct;
- (id)description;
- (BOOL)isRecording;
- (void)transferLogStoreManageableToCache;
- (id)fullLogIfInMemory;
- (id)fullLogStoreManageableWithError:(id *)arg1;
- (id)fullLogWithError:(id *)arg1;
- (id)_faultedLogStoreManageable:(id *)arg1;
- (id)_cachedLogStoreManageable;
- (void)tearDown;
- (id)buildMetricsReportFilePath;
- (BOOL)collectMetrics;
- (id)onDiskPath;
- (id)coverageArchiveFilePath;
- (id)coverageReportFilePath;
- (BOOL)hasCoverageData;
- (id)testableSummariesPlistFilePath;
@property(readonly, copy) NSDictionary *dictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1 logRecordManager:(id)arg2 error:(id *)arg3;
- (id)initWithLogStoreManageable:(id)arg1 entityIdentifier:(id)arg2 logRecordManager:(id)arg3;

@end

