//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDESchemeActionAbstractTestSummaryObject.h>

@class NSString;

@interface IDESchemeActionDummyTestSummary : IDESchemeActionAbstractTestSummaryObject
{
    NSString *_sentinelGUID;
}

- (void).cxx_destruct;
- (void)loadAttachmentsFromDirectory:(id)arg1;
- (void)loadDiagnosticsFromDirectory:(id)arg1;
- (BOOL)updateWithDictionaryRepresentation:(id)arg1;
- (id)dictionaryRepresentation;
- (unsigned long long)status;
- (id)identifier;
- (id)init;

@end

