//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTDispatchLock, IDESourceControlExtension, IDESourceControlRepository, NSDate, NSMutableArray, NSString;

@interface IDESourceControlWorkingCopyConfiguration : NSObject
{
    NSMutableArray *_branches;
    DVTDispatchLock *_branchesLock;
    NSDate *_branchesInvalidationDate;
    IDESourceControlRepository *_repository;
    NSString *_name;
    NSString *_uniqueIdentifier;
    IDESourceControlExtension *_sourceControlExtension;
    NSString *_remoteDistributedOrigin;
}

@property(copy) NSString *remoteDistributedOrigin; // @synthesize remoteDistributedOrigin=_remoteDistributedOrigin;
@property(retain) IDESourceControlExtension *sourceControlExtension; // @synthesize sourceControlExtension=_sourceControlExtension;
@property(readonly) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain) IDESourceControlRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (id)branchesWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_branchesWithToken:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)setBranches:(id)arg1;
@property(readonly) NSMutableArray *branches;
- (id)_stripBaseURLOrStartingSlash:(id)arg1;
- (id)_createBranchingURLWithRelativePath:(id)arg1;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1 sourceControlManager:(id)arg2;
- (id)initWithName:(id)arg1 identifier:(id)arg2 sourceControlExtension:(id)arg3 sourceControlManager:(id)arg4;
- (id)init;

@end

