//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/NSObject-Protocol.h>

@class IDESourceKitCodeCompletionOperation, NSString;

@protocol IDESourceKitOperationObserver <NSObject>
- (void)codeCompletionOperationWasCompleted:(IDESourceKitCodeCompletionOperation *)arg1;
- (void)workspaceClosed:(NSString *)arg1;
- (void)workspaceOpened:(NSString *)arg1;
- (void)serviceCrashed;
- (void)serviceWasStartedWithPID:(int)arg1;
@end

