//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDELogStoreManageable-Protocol.h>

@class DVTFilePath, DVTObservingToken, IDEActivityLogSection, IDEEntityIdentifier, IDESchemeActionCodeCoverage, IDETypeIdentifier, NSArray, NSMapTable, NSMutableArray, NSString;

@interface IDESchemeActionsInvocationRecord : NSObject <IDELogStoreManageable>
{
    NSMutableArray *_actions;
    NSMutableArray *_warningSummaries;
    NSMutableArray *_errorSummaries;
    NSMutableArray *_analyzerWarningSummaries;
    NSMutableArray *_testFailureSummaries;
    NSMutableArray *_testableSummaries;
    NSMapTable *_strongActionRecordsToStatusObservers;
    IDESchemeActionCodeCoverage *_coverageReport;
    BOOL _shouldClearExistingFileOnSave;
    BOOL _running;
    BOOL _archiveFetchable;
    BOOL _productFetchable;
    BOOL _remoteTestSummaryNeedsFetch;
    BOOL _remoteCodeCoverageNeedsFetch;
    NSString *_uniqueIdentifier;
    IDETypeIdentifier *_domainType;
    DVTFilePath *_filePath;
    NSString *_defaultFileName;
    IDEEntityIdentifier *_schemeIdentifier;
    DVTFilePath *_archivePath;
    NSString *_archiveName;
    unsigned long long _archiveSize;
    DVTFilePath *_productPath;
    NSString *_productName;
    unsigned long long _productSize;
    unsigned long long _warningCount;
    unsigned long long _errorCount;
    unsigned long long _analyzerWarningCount;
    unsigned long long _testsCount;
    unsigned long long _testsFailedCount;
    DVTFilePath *_creatingWorkspaceFilePath;
    id _remoteTestSummaryIdentifier;
    id _remoteCodeCoverageIdentifier;
    NSMutableArray *_performanceSignpostEvents;
    id _performanceSignpostNotificationToken;
    NSMutableArray *_completionBlocks;
    DVTObservingToken *_completionToken;
    NSString *_archiveGUID;
    NSString *_productGUID;
}

+ (id)keyPathsForValuesAffectingSimpleOperationStatus;
+ (id)keyPathsForValuesAffectingStatus;
+ (BOOL)updateSummariesFromDictionaryRepresentations:(id)arg1 withSummaryOwner:(id)arg2 summaryPropertyName:(id)arg3 summaryiVarArrayRef:(id *)arg4 summariesAreTestFailures:(BOOL)arg5;
+ (BOOL)automaticallyNotifiesObserversOfActions;
+ (id)keyPathsForValuesAffectingIsRecording;
+ (id)makeInstanceWithContentsOfFile:(id)arg1 error:(id *)arg2;
+ (BOOL)invocationRecordExistsAtFilePath:(id)arg1;
+ (void)invocationRecordWithLocalActionResultFilePath:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSString *productGUID; // @synthesize productGUID=_productGUID;
@property(retain, nonatomic) NSString *archiveGUID; // @synthesize archiveGUID=_archiveGUID;
@property(retain) DVTObservingToken *completionToken; // @synthesize completionToken=_completionToken;
@property(retain) NSMutableArray *completionBlocks; // @synthesize completionBlocks=_completionBlocks;
@property(retain) id performanceSignpostNotificationToken; // @synthesize performanceSignpostNotificationToken=_performanceSignpostNotificationToken;
@property(retain) NSMutableArray *performanceSignpostEvents; // @synthesize performanceSignpostEvents=_performanceSignpostEvents;
@property(nonatomic) BOOL remoteCodeCoverageNeedsFetch; // @synthesize remoteCodeCoverageNeedsFetch=_remoteCodeCoverageNeedsFetch;
@property(copy, nonatomic) id remoteCodeCoverageIdentifier; // @synthesize remoteCodeCoverageIdentifier=_remoteCodeCoverageIdentifier;
@property(nonatomic) BOOL remoteTestSummaryNeedsFetch; // @synthesize remoteTestSummaryNeedsFetch=_remoteTestSummaryNeedsFetch;
@property(copy, nonatomic) id remoteTestSummaryIdentifier; // @synthesize remoteTestSummaryIdentifier=_remoteTestSummaryIdentifier;
@property(retain, nonatomic) DVTFilePath *creatingWorkspaceFilePath; // @synthesize creatingWorkspaceFilePath=_creatingWorkspaceFilePath;
@property(retain, nonatomic) NSArray *testableSummaries; // @synthesize testableSummaries=_testableSummaries;
@property(retain, nonatomic) NSMutableArray *testFailureSummaries; // @synthesize testFailureSummaries=_testFailureSummaries;
@property(retain, nonatomic) NSMutableArray *analyzerWarningSummaries; // @synthesize analyzerWarningSummaries=_analyzerWarningSummaries;
@property(retain, nonatomic) NSMutableArray *errorSummaries; // @synthesize errorSummaries=_errorSummaries;
@property(retain, nonatomic) NSMutableArray *warningSummaries; // @synthesize warningSummaries=_warningSummaries;
@property(nonatomic) unsigned long long testsFailedCount; // @synthesize testsFailedCount=_testsFailedCount;
@property(nonatomic) unsigned long long testsCount; // @synthesize testsCount=_testsCount;
@property(nonatomic) unsigned long long analyzerWarningCount; // @synthesize analyzerWarningCount=_analyzerWarningCount;
@property(nonatomic) unsigned long long errorCount; // @synthesize errorCount=_errorCount;
@property(nonatomic) unsigned long long warningCount; // @synthesize warningCount=_warningCount;
@property(nonatomic) unsigned long long productSize; // @synthesize productSize=_productSize;
@property(retain, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(retain, nonatomic) DVTFilePath *productPath; // @synthesize productPath=_productPath;
@property(nonatomic, getter=isProductFetchable) BOOL productFetchable; // @synthesize productFetchable=_productFetchable;
@property(nonatomic, getter=isArchiveFetchable) BOOL archiveFetchable; // @synthesize archiveFetchable=_archiveFetchable;
@property(nonatomic) unsigned long long archiveSize; // @synthesize archiveSize=_archiveSize;
@property(retain, nonatomic) NSString *archiveName; // @synthesize archiveName=_archiveName;
@property(retain, nonatomic) DVTFilePath *archivePath; // @synthesize archivePath=_archivePath;
@property(copy) IDEEntityIdentifier *schemeIdentifier; // @synthesize schemeIdentifier=_schemeIdentifier;
@property(readonly, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(nonatomic, getter=isRunning) BOOL running; // @synthesize running=_running;
@property(nonatomic) BOOL shouldClearExistingFileOnSave; // @synthesize shouldClearExistingFileOnSave=_shouldClearExistingFileOnSave;
@property(copy) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(retain) IDETypeIdentifier *domainType; // @synthesize domainType=_domainType;
@property(readonly, copy) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long simpleOperationStatus;
@property(readonly, nonatomic) long long status;
@property(readonly, nonatomic) IDESchemeActionCodeCoverage *aggregateCoverageReport;
- (BOOL)updateLocalTestSummaryWithRemoteTestSummary:(id)arg1 error:(id *)arg2;
- (BOOL)saveTestSummariesWithError:(id *)arg1;
- (id)testSummaryFormatVersionString;
- (id)localTestSummaryFilePath;
- (void)_updateTestableSummaries;
- (void)_updateSummaries;
- (void)tearDownObserversForSchemeActionRecord:(id)arg1;
- (void)setUpObserversForSchemeActionRecord:(id)arg1;
- (void)updateAllSchemeActionRecordDirectoryFilePaths;
- (id)filePathForSchemeActionRecordDirectoryWithSchemeCommand:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)makeActionRecordWithSchemeCommand:(id)arg1 schemeTask:(long long)arg2 runDestination:(id)arg3;
@property(readonly, copy) NSString *overrideMetricsPath;
@property(readonly) BOOL collectMetrics;
@property(readonly, copy) DVTFilePath *coverageArchiveFilePath;
@property(readonly, copy) DVTFilePath *coverageReportFilePath;
@property(readonly) BOOL hasCoverageData;
@property(readonly, copy) DVTFilePath *testableSummariesPlistFilePath;
@property(readonly, copy) NSString *defaultFileName; // @synthesize defaultFileName=_defaultFileName;
@property(readonly) IDEActivityLogSection *auxiliaryLogSection;
@property(readonly) IDEActivityLogSection *logSection;
@property(readonly) unsigned long long totalNumberOfAnalyzerResults;
@property(readonly) unsigned long long totalNumberOfWarnings;
@property(readonly) unsigned long long totalNumberOfErrors;
@property(readonly) unsigned long long totalNumberOfTestFailures;
@property(readonly) BOOL isRecording;
@property(readonly) double timeStoppedRecording;
@property(readonly) double timeStartedRecording;
@property(readonly, copy) NSString *title;
@property(readonly, copy) NSString *signature;
- (void)addCompletionBlock:(CDUnknownBlockType)arg1;
- (BOOL)writeToFile:(id)arg1 error:(id *)arg2;
@property(readonly, copy) NSString *description;
- (void)close;
- (BOOL)loadActionsTestSummariesAndCoverageFromResultBundle:(id *)arg1;
- (BOOL)updateWithDictionaryRepresentation:(id)arg1;
- (id)dictionaryRepresentation;
- (void)saveWithCompletionBlock:(CDUnknownBlockType)arg1;
@property(readonly) BOOL canSave;
- (void)_stopCollectingPerformanceSignposts;
- (void)_startCollectingPerformanceSignposts;
- (void)dealloc;
- (void)saveSparseInvocationRecordToFilePath:(id)arg1 testIdentifiers:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithFilePath:(id)arg1 error:(id *)arg2;
- (id)initLocalRecordWithWorkspace:(id)arg1;
- (id)_init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

