//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/DVTInvalidation-Protocol.h>

@class DVTOperationGroup, IDETestDestination, IDETestRunSpecification, NSArray, NSURL;
@protocol IDETestTargetRunnerEvents;

@protocol IDETestTargetRunner <DVTInvalidation>
@property(readonly) NSURL *artifactsDirectory;
@property(readonly) BOOL finished;
@property(readonly) NSArray *testResults;
@property(readonly) IDETestRunSpecification *testRunSpecification;
@property(readonly) IDETestDestination *testDestination;
@property(readonly) DVTOperationGroup *operation;
@property __weak id <IDETestTargetRunnerEvents> testEventsObserver;
@end

