//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSObject;
@protocol IDETestTargetLoadBalancerDelegate, OS_dispatch_queue;

@protocol IDETestTargetLoadBalancer
@property(retain) NSObject<OS_dispatch_queue> *delegateQueue;
@property __weak id <IDETestTargetLoadBalancerDelegate> delegate;
- (void)workQueueDidChange:(NSArray *)arg1;
- (void)stop;
- (void)start;
@end

