//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol IDETestOperationStateMachineDelegate, OS_dispatch_queue;

@interface IDETestOperationStateMachine : NSObject
{
    BOOL _testPlanDidStartExecuting;
    BOOL _readyForTestBundleToConnect;
    BOOL _launchSessionInitialIntensiveFileIODone;
    BOOL _hasFinalized;
    BOOL _finalizationPending;
    id <IDETestOperationStateMachineDelegate> _delegate;
    NSString *_finalizationDescription;
    NSObject<OS_dispatch_queue> *_queue;
    CDStruct_3e9da45b _timeouts;
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) NSString *finalizationDescription; // @synthesize finalizationDescription=_finalizationDescription;
@property(nonatomic, getter=isFinalizationPending) BOOL finalizationPending; // @synthesize finalizationPending=_finalizationPending;
@property(nonatomic) BOOL hasFinalized; // @synthesize hasFinalized=_hasFinalized;
@property(readonly) CDStruct_3e9da45b timeouts; // @synthesize timeouts=_timeouts;
@property(readonly) __weak id <IDETestOperationStateMachineDelegate> delegate; // @synthesize delegate=_delegate;
@property BOOL launchSessionInitialIntensiveFileIODone; // @synthesize launchSessionInitialIntensiveFileIODone=_launchSessionInitialIntensiveFileIODone;
@property BOOL readyForTestBundleToConnect; // @synthesize readyForTestBundleToConnect=_readyForTestBundleToConnect;
@property BOOL testPlanDidStartExecuting; // @synthesize testPlanDidStartExecuting=_testPlanDidStartExecuting;
- (void).cxx_destruct;
- (void)testmanagerdConnectionLost;
- (void)receivedDiagnosticReportForTestRunnerProcessWithDescription:(id)arg1;
- (void)launchSessionConnectionLost;
- (void)launchSessionExitedWithCode:(int)arg1;
- (void)launchSessionExpired;
- (id)_runnerExitDescriptionWithMessage:(id)arg1;
- (void)_finalizeWhenReadyWithDescription:(id)arg1;
- (void)_ensureFinalizationWithinTimeInterval:(double)arg1 withCandidateDescription:(id)arg2;
- (void)launchSessionInitialIntensiveFileIODoneState;
- (void)_queue_finalize;
- (id)initWithDelegate:(id)arg1;
- (id)initWithDelegate:(id)arg1 timeouts:(CDStruct_3e9da45b)arg2;

@end

