//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface IDETestSummariesBuilderWorkerState : NSObject
{
    double _duration;
    NSMutableArray *_testSuiteStack;
    NSMutableArray *_performanceMetricSummaries;
    NSMutableArray *_failureSummaries;
    NSMutableArray *_activitySummaries;
    NSMutableArray *_currentActivityStack;
}

@property(readonly) NSMutableArray *currentActivityStack; // @synthesize currentActivityStack=_currentActivityStack;
@property(readonly) NSMutableArray *activitySummaries; // @synthesize activitySummaries=_activitySummaries;
@property(readonly) NSMutableArray *failureSummaries; // @synthesize failureSummaries=_failureSummaries;
@property(readonly) NSMutableArray *performanceMetricSummaries; // @synthesize performanceMetricSummaries=_performanceMetricSummaries;
@property(readonly) NSMutableArray *testSuiteStack; // @synthesize testSuiteStack=_testSuiteStack;
@property double duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (id)init;

@end

