//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSDate, OS_dispatch_queue;
@protocol _TtP13IDEFoundation31IDETestDaemonControllerObserver_;

@protocol IDETestDaemonController
@property(nonatomic, copy) CDUnknownBlockType selfDiagnosisIssueHandler;
- (void)requestSpindumpWithCompletion:(void (^)(NSData *, NSError *))arg1;
@property(nonatomic, readonly) BOOL canRequestSpindumps;
- (void)collectLogArchiveFromDate:(NSDate *)arg1 completion:(void (^)(NSString *, NSError *))arg2;
@property(nonatomic, readonly) BOOL canRequestLogArchives;
- (void)addProcessNamesToMonitoredCrashReports:(NSArray *)arg1 completion:(void (^)(NSError *))arg2;
@property(nonatomic, readonly) BOOL canRequestCrashReports;
- (void)authorizeProcessWithIdentifier:(int)arg1 completion:(void (^)(NSError *))arg2;
@property(nonatomic, readonly) BOOL canAuthorizeProcesses;
- (void)removeObserver:(id <_TtP13IDEFoundation31IDETestDaemonControllerObserver_>)arg1;
- (void)addObserver:(id <_TtP13IDEFoundation31IDETestDaemonControllerObserver_>)arg1 queue:(OS_dispatch_queue *)arg2;
- (void)activate;
@end

