//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEWorkspaceSettings.h>

@class DVTObservingToken;

@interface IDEWorkspaceSharedSettings : IDEWorkspaceSettings
{
    DVTObservingToken *_workspaceLoadingObservingToken;
}

- (void).cxx_destruct;
- (void)setBuildSystemType:(int)arg1;
- (void)primitiveInvalidate;
- (void)_propagateBuildSystemSelectionForWorkspace:(id)arg1;
- (id)initWithWorkspace:(id)arg1;
- (void)saveSettings;
@property BOOL autocreateContextsIfNeeded;
- (id)settingsOwnership;

@end

