//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

@interface IPAToolCoalescedThinningVariant : NSObject
{
    // Error parsing type: , name: variants
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hashValue;
- (id)initWithVariants:(id)arg1;
@property(nonatomic, readonly) NSSet *variants; // @synthesize variants;

@end

