//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IPAToolDevice, NSString;

@interface IPAToolThinningVariant : NSObject
{
    // Error parsing type: , name: device
    // Error parsing type: , name: deploymentTarget
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hashValue;
- (id)initWithDevice:(id)arg1 deploymentTarget:(id)arg2;
@property(nonatomic, readonly) NSString *deploymentTarget; // @synthesize deploymentTarget;
@property(nonatomic, readonly) IPAToolDevice *device; // @synthesize device;

@end

