//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/XCTDaemonSessionDelegate-Protocol.h>

@class NSData, NSString;
@protocol XCTDaemonControlSession;

@protocol XCTDaemonControlSessionDelegate <XCTDaemonSessionDelegate>
- (void)daemonControlSession:(id <XCTDaemonControlSession>)arg1 didReportSelfDiagnosisIssue:(NSString *)arg2 description:(NSString *)arg3;
- (void)daemonControlSession:(id <XCTDaemonControlSession>)arg1 didReceiveDebugLogMessage:(NSString *)arg2;
- (void)daemonControlSession:(id <XCTDaemonControlSession>)arg1 didReceiveCrashReportData:(NSData *)arg2 fileName:(NSString *)arg3;
@end

