//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEiOSSupportCore/_RuntimeProfileWorker.h>

@interface _RuntimeProfileWorkerInternal : _RuntimeProfileWorker
{
}

- (BOOL)downloadRuntimeProfilesFromDeviceDirectories:(id)arg1 toLocalDirectory:(id)arg2 error:(id *)arg3;
- (id)createRuntimeProfileDirectory:(id *)arg1;

@end

