//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSCore/XCSDevice.h>

@class XCSIntegration;

@interface XCSTestDevice : XCSDevice
{
    XCSIntegration *integration;
}

@property(nonatomic) __weak XCSIntegration *integration; // @synthesize integration;
- (void).cxx_destruct;
- (id)description;

@end

