//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSDynamicNamedColor.h>

@class NSAppearance, NSColor;

@interface _DVTDynamicColor : NSDynamicNamedColor
{
    CDUnknownBlockType _resolver;
    NSColor *_cachedResolvedColor;
    NSAppearance *_lastAppearance;
}

- (void).cxx_destruct;
- (void)set;
- (struct CGColor *)CGColor;
- (id)colorSpaceName;
- (id)resolvedColor;
- (id)initWithResolver:(CDUnknownBlockType)arg1;

@end

