//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTKit/DVTFilterSession-Protocol.h>

@class DVTFilterExpression, DVTFilterExpressionController;

@interface _DVTFilterSession : NSObject <DVTFilterSession>
{
    BOOL _isCancelled;
    long long _filterProgress;
    DVTFilterExpressionController *_filterExpressionController;
    DVTFilterExpression *_filterExpression;
}

@property(retain) DVTFilterExpression *filterExpression; // @synthesize filterExpression=_filterExpression;
@property(readonly) DVTFilterExpressionController *filterExpressionController; // @synthesize filterExpressionController=_filterExpressionController;
@property long long filterProgress; // @synthesize filterProgress=_filterProgress;
@property BOOL isCancelled; // @synthesize isCancelled=_isCancelled;
- (void).cxx_destruct;
- (void)setMatches:(id)arg1;
- (id)initWithFilterExpressionController:(id)arg1 filterExpression:(id)arg2;

@end

