//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/_TtC6DVTKitP33_BA9CC060444A6B2FA90D6602DDD5C31E15_LoadedIconSpec.h>

@interface _TtC6DVTKitP33_BA9CC060444A6B2FA90D6602DDD5C31E29_IconSpecLoadedFromSourceFile : _TtC6DVTKitP33_BA9CC060444A6B2FA90D6602DDD5C31E15_LoadedIconSpec
{
    // Error parsing type: , name: _iconSetSpec
}

- (CDUnknownBlockType).cxx_destruct;

@end

