//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTOutlineView.h>

@interface _TtC6DVTKit22DVTExplorerOutlineView : DVTOutlineView
{
    // Error parsing type: , name: preloadAction
    // Error parsing type: , name: trackingArea
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1;
- (void)mouseMoved:(id)arg1;
- (void)updateTrackingAreas;

@end

