//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _TtC6DVTKit27DVTIconSpecificationContext : NSObject
{
    // Error parsing type: , name: iconSetVendor
    // Error parsing type: , name: _intendedSize
    // Error parsing type: , name: _iconSetName
    // Error parsing type: , name: _iconName
    // Error parsing type: , name: _initialAspects
    // Error parsing type: , name: cacheKey.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;

@end

