//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColorWell.h>

@protocol DVTColorWellDelegate;

@interface DVTColorWell : NSColorWell
{
    id <DVTColorWellDelegate> _delegate;
    BOOL _delegateRespondsToShouldSetColor;
}

- (void).cxx_destruct;
- (void)setColor:(id)arg1;
@property __weak id <DVTColorWellDelegate> delegate; // @synthesize delegate=_delegate;

@end

