//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/NSObject-Protocol.h>

@class DVTDisclosureHeaderView;

@protocol DVTDisclosureHeaderViewDelegate <NSObject>
- (void)disclosureHeaderView:(DVTDisclosureHeaderView *)arg1 didChangeDisclosedState:(BOOL)arg2;
@end

