//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/NSObject-Protocol.h>

@class DVTCompoundFilterExpression, DVTFilterExpression, NSArray, NSString;

@protocol DVTFilterExpressionPresentationDelegate <NSObject>
@property(readonly) NSString *filterFieldAccessibilityDescription;
@property(readonly) NSString *filterFieldToolTip;
- (NSString *)editingStringForFilterExpression:(DVTFilterExpression *)arg1;
- (NSString *)menuDisplayStringForFilterExpression:(DVTFilterExpression *)arg1;
- (NSString *)fieldDisplayStringForFilterExpression:(DVTFilterExpression *)arg1;
- (NSArray *)validFilterExpressionsForExpressions:(NSArray *)arg1 currentFilterExpression:(DVTFilterExpression *)arg2;
- (DVTFilterExpression *)filterExpressionForText:(NSString *)arg1 isComplete:(BOOL)arg2 currentFilterExpression:(DVTFilterExpression *)arg3;
- (NSString *)titleForFilterIdentifier:(NSString *)arg1;

@optional
- (NSArray *)filterExpressionCompletionsForText:(NSString *)arg1 currentFilterExpression:(DVTFilterExpression *)arg2;
- (NSArray *)textFragmentsForFilterExpression:(DVTCompoundFilterExpression *)arg1;
- (NSArray *)relatedFilterExpressionsIncludingExpression:(DVTFilterExpression *)arg1;
- (NSArray *)filterExpressionsForAdditionalFilteringOptionsMenu;
- (NSArray *)buttonsForCustomFilterExpressions;
@end

