//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextAttachmentCell.h>

@class DVTTextFold, NSView;

@interface NSTextAttachmentCell (DVTAvoidingPrivatesOnParade)
@property(readonly) BOOL dvt_isSourceCodeTreeNodeInlineTokenAttachmentCell;
@property(readonly) __weak DVTTextFold *dvt_foldForTextFoldInlineTokenAttachmentCells;
@property(retain) NSView *dvt_markupViewForMarkupViewTextAttachmentCells;
@end

