//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7llbuild11BuildSystem : SwiftObject
{
    // Error parsing type: , name: buildFile
    // Error parsing type: , name: delegate
    // Error parsing type: , name: _system
    // Error parsing type: , name: _cEnvironment
    // Error parsing type: , name: toolWrappers
}

@end

