//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7llbuildP33_397EF089548232B6CB5F24656ADE37CF11TaskWrapper : SwiftObject
{
    // Error parsing type: , name: engine
    // Error parsing type: , name: task
    // Error parsing type: , name: taskInternal
}

@end

