//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC30GitLabSelfHostBuiltInExtension33XCSourceControlHostRequestContext : NSObject
{
    // Error parsing type: , name: context
    // Error parsing type: , name: account
    // Error parsing type: , name: executor
    // Error parsing type: , name: endpointURL
    // Error parsing type: , name: session
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

