//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBiOSDeviceIconDescription;

@interface IBiOSDeviceIconGenerationInstance : NSObject
{
    BOOL _rotated;
    IBiOSDeviceIconDescription *_iconDescription;
    CDUnknownBlockType _customizationBlock;
}

@property(readonly, nonatomic) CDUnknownBlockType customizationBlock; // @synthesize customizationBlock=_customizationBlock;
@property(readonly, nonatomic, getter=isRotated) BOOL rotated; // @synthesize rotated=_rotated;
@property(readonly, nonatomic) IBiOSDeviceIconDescription *iconDescription; // @synthesize iconDescription=_iconDescription;
- (void).cxx_destruct;
- (id)initWithDescription:(id)arg1 rotated:(BOOL)arg2 customizationBlock:(CDUnknownBlockType)arg3;

@end

