//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBiOSDeviceIconGenerationInstance;

@interface IBiOSDeviceIconGenerationInstanceContext : NSObject
{
    IBiOSDeviceIconGenerationInstance *_instance;
    double _pointsPerInch;
}

@property(readonly, nonatomic) double pointsPerInch; // @synthesize pointsPerInch=_pointsPerInch;
@property(readonly, nonatomic) IBiOSDeviceIconGenerationInstance *instance; // @synthesize instance=_instance;
- (void).cxx_destruct;
- (id)initWithInstance:(id)arg1 pointsPerInch:(double)arg2;

@end

