//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBCocoaTouchDocumentInspectorViewController.h>

@interface IBiOSDocumentInspectorViewController : IBCocoaTouchDocumentInspectorViewController
{
}

+ (id)documentPlatform;
- (void)didApplyDependencyValue:(id)arg1 toDependency:(id)arg2 forDocument:(id)arg3;
- (id)alertAccessoryViewForDisablingConfigurations;
- (void)finishDisablingConfigurationsAndAutolayout:(BOOL)arg1 forDocuments:(id)arg2 withAlert:(id)arg3;

@end

