//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderiOSIntegration/IBiOSIdiom.h>

@class IBCocoaTouchDeviceSubtype;

@interface IBIPadIdiom : IBiOSIdiom
{
    IBCocoaTouchDeviceSubtype *_iPad12_9InchSubtype;
    IBCocoaTouchDeviceSubtype *_iPad10_5InchSubtype;
    IBCocoaTouchDeviceSubtype *_iPad9_7InchSubtype;
}

- (void).cxx_destruct;
- (struct CGSize)pageSheetFixedSizeForOrientationMetrics:(id)arg1 screenMetrics:(id)arg2;
- (struct CGSize)formSheetFixedSizeForOrientationMetrics:(id)arg1 screenMetrics:(id)arg2;
- (BOOL)detailUsesSplitScreen:(id)arg1 screenMetrics:(id)arg2;
- (BOOL)masterUsesSplitScreen:(id)arg1 screenMetrics:(id)arg2;
- (long long)legacyTypeForScreenMetrics:(id)arg1;
- (id)screenMetricsForLegacyType:(long long)arg1;
- (double)defaultEditingZoomFactorForCanvasBackingScaleFactor:(double)arg1;
- (id)supportedOSVersions;
- (id)supportedAdBannerSizes;
- (long long)defaultOrientationForArchiving;
- (id)defaultOrientationMetrics;
- (id)defaultSubtypeForArchiving;
- (id)defaultSubtype;
- (id)splitViewDetailMemberConfigurationForOrientationMetrics:(id)arg1 screenMetrics:(id)arg2;
- (id)splitViewMasterMemberConfigurationForOrientationMetrics:(id)arg1 screenMetrics:(id)arg2;
- (BOOL)supportsBranchingForTraitVariations;
- (id)backwardsDeploymentConfiguration;
- (BOOL)_isFullScreenScreenMetrics:(id)arg1;
- (id)iPad9_7InchFullscreenScreenMetrics;
- (id)presentationOrderedConcreteSubtypes;
- (void)populateSubtypes:(id)arg1;
- (long long)deviceIconIdiom;
- (id)iPad12_9InchSubtype;
- (id)iPad10_5InchSubtype;
- (id)iPad9_7InchSubtype;
- (id)presentationOrderedSiblingIdioms;
- (id)effectiveIdiomForProvidingDefaultSubtypesInDocument:(id)arg1;
- (id)resourceIdiomVariant;
- (id)designatedIdiomForConfigurations;
- (BOOL)ignoresStatusBarForUIBarStyleComputation;
- (BOOL)supportsSearchBarsEmbeddedInBarButtonItems;
- (BOOL)supportsTopToolbars;
- (BOOL)supportsForceTouchSeguesInDocument:(id)arg1;
- (long long)deviceInterfaceIdiom;
- (id)icon;
- (id)xibArchiveType;
- (id)colorListName;
- (id)archiveIdentifier;
- (id)identifier;
- (id)idiomName;

@end

