//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerFoundation/GPUTraceGroupItem.h>

__attribute__((visibility("hidden")))
@interface GPUMTLTraceGroupItem : GPUTraceGroupItem
{
    unsigned int _objectReceiverType;
}

- (id)APIItem;
- (id)label;
- (int)labelSource;
- (id)initWithController:(id)arg1 parent:(id)arg2 label:(id)arg3 objectID:(unsigned long long)arg4 objectType:(unsigned int)arg5 functionIndex:(int)arg6;

@end

