//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerMTLSupport/NSObject-Protocol.h>

@class NSArray;
@protocol DYResource;

@protocol GPUTraceDisplaySet <NSObject>
@property(readonly, nonatomic) NSArray *elementIDs;
@property(readonly, nonatomic) unsigned int numElements;

@optional
@property(retain) id <DYResource> solidImage;
@property(retain) id <DYResource> outlineImage;
@property(retain) id <DYResource> wireframeImage;
@end

