//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface GPUTracePostVertexTransformBufferViewerAdaptor : NSObject
{
}

+ (id)bufferViewerData:(id)arg1 baseVertex:(long long)arg2 baseInstance:(unsigned long long)arg3 outRowsPerInstance:(unsigned long long *)arg4;

@end

