//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

__attribute__((visibility("hidden")))
@interface _TtC23DNTDocumentationSupport24BulkEnumerationOperation : NSOperation
{
    // Error parsing type: , name: documentationService
    // Error parsing type: , name: dataRange
    // Error parsing type: , name: entitySuccessHandler
    // Error parsing type: , name: entityParseFailureHandler
    // Error parsing type: , name: imageHandler
    // Error parsing type: , name: otherFailureHandler
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)main;

@end

