//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DNTDocumentationSupport/DNTDisplayTreeIndexItem-Protocol.h>

@class NSString, NSURL;
@protocol DNTDisplayTreeIndexItem;

@interface DNTDisplayTreeItem : NSObject <DNTDisplayTreeIndexItem>
{
    // Error parsing type: , name: info
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (BOOL)isGroup;
@property(nonatomic, readonly) long long languageEntityKind;
@property(nonatomic, readonly) NSString *name;
@property(nonatomic, readonly) int rawLanguage;
@property(nonatomic, readonly) unsigned char type;
@property(nonatomic, readonly) id <DNTDisplayTreeIndexItem> parent;
@property(nonatomic, readonly) NSURL *url;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
- (id)copyWithZone:(void *)arg1;

// Remaining properties
@property(nonatomic, readonly) BOOL group;

@end

