//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DNTDocumentationSupport/DNTDisplayTreeIndexDeserializationDelegate-Protocol.h>
#import <DNTDocumentationSupport/NSObject-Protocol.h>

@class NSError;

@protocol DNTDisplayTreeIndexDelegate <DNTDisplayTreeIndexDeserializationDelegate, NSObject>

@optional
- (void)indexDidFinishLoading;
- (void)indexFailedLoadingWithError:(NSError *)arg1;
@end

