//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (SCNAdditions)
+ (id)scn_colorWithC3DColor:(const struct C3DColor4 *)arg1;
- (struct C3DColor4)scn_C3DColorIgnoringColorSpace:(BOOL)arg1 success:(char *)arg2;
@end

