//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (SCNJSExtensions)
+ (id)color:(double)arg1:(double)arg2:(double)arg3:(double)arg4;
- (double)a;
- (double)b;
- (double)g;
- (double)r;
@end

