//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTLayoutView_ML.h>

@class NSString, NSTextField;

@interface IDEScriptingDefinitionPlaceholderView : DVTLayoutView_ML
{
    NSTextField *_placeholderTextField;
}

- (void).cxx_destruct;
- (void)layoutBottomUp;
@property(copy) NSString *placeholderString;
- (id)initWithFrame:(struct CGRect)arg1;

@end

