//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC29BitbucketHostBuiltInExtension33XCSourceControlHostRequestContext.h"

__attribute__((visibility("hidden")))
@interface _TtC29BitbucketHostBuiltInExtension32BitbucketCreateRepositoryRequest : _TtC29BitbucketHostBuiltInExtension33XCSourceControlHostRequestContext
{
    // Error parsing type: , name: repoName
    // Error parsing type: , name: desc
    // Error parsing type: , name: homepage
    // Error parsing type: , name: private
    // Error parsing type: , name: owner
}

- (CDUnknownBlockType).cxx_destruct;

@end

