//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <GameToolsFoundation/NSSecureCoding-Protocol.h>

@class NSImage;

@interface GTFActionLibraryTargetThumbnail : NSObject <NSSecureCoding>
{
    BOOL _isIcon;
    NSImage *_image;
}

+ (BOOL)supportsSecureCoding;
+ (id)targetThumbnailWithImage:(id)arg1;
@property(nonatomic) BOOL isIcon; // @synthesize isIcon=_isIcon;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithImage:(id)arg1;

@end

