//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GameToolsFoundation/GTFActionModel.h>

@class NSString;

@interface SKActionReference : GTFActionModel
{
    NSString *_referenceName;
}

+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSString *referenceName; // @synthesize referenceName=_referenceName;
- (void).cxx_destruct;
- (id)getSKAction;
@property(readonly, nonatomic) NSString *referenceFilename;
- (id)actionInfoString;
- (id)actionColor;
- (id)actionName;
- (long long)actionType;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithReferenceName:(id)arg1;

@end

