//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC36GitHubEnterpriseHostBuiltInExtension14GitHubEndpoint.h"

__attribute__((visibility("hidden")))
@interface _TtC36GitHubEnterpriseHostBuiltInExtension24GitHubEnterpriseEndpoint : _TtC36GitHubEnterpriseHostBuiltInExtension14GitHubEndpoint
{
}

- (id)init;
- (BOOL)shouldAllowAvatarFrom:(id)arg1 withAccount:(id)arg2;
- (void)avatar:(id)arg1 account:(id)arg2 email:(id)arg3 size:(unsigned int)arg4 reply:(CDUnknownBlockType)arg5;
- (void)avatar:(id)arg1 account:(id)arg2 username:(id)arg3 size:(unsigned int)arg4 reply:(CDUnknownBlockType)arg5;
- (void)loginHelpURL:(id)arg1 url:(id)arg2 username:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)requestPersonalAccessToken:(id)arg1 account:(id)arg2 twoFactorCode:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)capabilities:(id)arg1 account:(id)arg2 reply:(CDUnknownBlockType)arg3;

@end

