//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC36GitHubEnterpriseHostBuiltInExtension33XCSourceControlHostRequestContext.h"

__attribute__((visibility("hidden")))
@interface _TtC36GitHubEnterpriseHostBuiltInExtension32GitHubPersonalAccessTokenRequest : _TtC36GitHubEnterpriseHostBuiltInExtension33XCSourceControlHostRequestContext
{
    // Error parsing type: , name: twoFactorCode
    // Error parsing type: , name: note
}

- (CDUnknownBlockType).cxx_destruct;

@end

