//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL, XCSourceControlHostAccount, XCSourceControlHostOwner, XCSourceControlHostRepository;

@protocol XCSourceControlHostEndpoint <NSObject>
- (BOOL)shouldAllowAvatarFrom:(NSURL *)arg1 withAccount:(NSURL *)arg2;
- (void)username:(NSString *)arg1 url:(NSURL *)arg2 reply:(void (^)(NSString *))arg3;
- (void)listSSHKeys:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 reply:(void (^)(NSArray *, NSError *))arg3;
- (void)validateSSHKey:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 publicSSHKey:(NSString *)arg3 reply:(void (^)(BOOL, NSError *))arg4;
- (void)repositoryMetadata:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 repository:(XCSourceControlHostRepository *)arg3 reply:(void (^)(XCSourceControlHostRepository *, NSError *))arg4;
- (void)uploadSSHKey:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 publicSSHKey:(NSString *)arg3 reply:(void (^)(NSError *))arg4;
- (void)user:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 reply:(void (^)(XCSourceControlHostOwner *, NSError *))arg3;
- (void)requestAuthCode:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 reply:(void (^)(NSError *))arg3;
- (void)searchRepositories:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 query:(NSString *)arg3 reply:(void (^)(NSDictionary *, NSError *))arg4;
- (void)createRepository:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 owner:(XCSourceControlHostOwner *)arg3 name:(NSString *)arg4 description:(NSString *)arg5 homepage:(NSURL *)arg6 private:(BOOL)arg7 reply:(void (^)(XCSourceControlHostRepository *, NSError *))arg8;
- (void)membership:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 options:(long long)arg3 reply:(void (^)(NSArray *, NSError *))arg4;
- (void)validateCredentials:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 reply:(void (^)(NSString *, NSError *))arg3;
- (void)repositories:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 type:(unsigned long long)arg3 reply:(void (^)(NSDictionary *, NSError *))arg4;
- (void)requestPersonalAccessToken:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 twoFactorCode:(NSString *)arg3 reply:(void (^)(NSString *, NSString *, NSError *))arg4;
- (void)unstar:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 repository:(XCSourceControlHostRepository *)arg3 reply:(void (^)(NSError *))arg4;
- (void)star:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 repository:(XCSourceControlHostRepository *)arg3 reply:(void (^)(NSError *))arg4;
- (void)avatar:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 username:(NSString *)arg3 size:(unsigned int)arg4 reply:(void (^)(NSImage *, NSError *))arg5;
- (void)avatar:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 email:(NSString *)arg3 size:(unsigned int)arg4 reply:(void (^)(NSImage *, NSError *))arg5;
- (void)loginHelpURL:(NSString *)arg1 url:(NSURL *)arg2 username:(NSString *)arg3 reply:(void (^)(NSURL *))arg4;
- (void)webURLComponents:(void (^)(NSString *, NSString *, NSString *))arg1;
- (void)webURL:(NSURL *)arg1 sha:(NSString *)arg2 reply:(void (^)(NSURL *))arg3;
- (void)webURL:(NSURL *)arg1 branch:(NSString *)arg2 reply:(void (^)(NSURL *))arg3;
- (void)webURL:(NSURL *)arg1 tag:(NSString *)arg2 reply:(void (^)(NSURL *))arg3;
- (void)webURL:(NSURL *)arg1 reply:(void (^)(NSURL *))arg2;
- (void)capabilities:(NSString *)arg1 account:(XCSourceControlHostAccount *)arg2 reply:(void (^)(unsigned long long))arg3;
- (void)cancelOperation:(NSString *)arg1 reply:(void (^)(NSError *))arg2;
@end

