//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderGroup.h>

@interface IDEIntentBuilderIntentGroup : IDEIntentBuilderGroup
{
}

+ (id)defaultItemName;
+ (Class)itemClass;
- (void)updateWithArray:(id)arg1;
@property(readonly, nonatomic) long long type;
- (id)itemWithIdentifier:(id)arg1;
- (void)addItem:(id)arg1;

@end

