//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEIntentBuilderCore/NSObject-Protocol.h>

@class NSArray, NSDictionary;

@protocol IDEIntentBuilderDictionaryConvertible <NSObject>
- (NSDictionary *)dictionaryRepresentation;

@optional
- (void)updateWithArray:(NSArray *)arg1;
- (void)updateWithDictionary:(NSDictionary *)arg1;
@end

