//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DTXChannel;

@interface DVTiOSScreenshotClient : NSObject
{
    DTXChannel *_channel;
}

@property(retain) DTXChannel *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (id)requestScreenshotWithError:(id *)arg1;
- (void)dealloc;
- (id)initWithConnection:(id)arg1;

@end

