//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEiOSSupportCore/DVTiOSDevice.h>

@class NSArray;

@interface DVTiOSDevice (DVTDevicesWindowInternalSummary)
+ (id)keyPathsForValuesAffectingDvtDevicesWindow_canSSH;
+ (id)keyPathsForValuesAffectingDeviceSummaryInternalPropertyDictionaries;
+ (id)keyPathsForValuesAffectingDvtDevicesWindow_isWirelessEnabled;
+ (id)keyPathsForValuesAffectingDvtDevicesWindow_rsyncPort;
+ (id)keyPathsForValuesAffectingDvtDevicesWindow_remoteSSHPort;
+ (id)keyPathsForValuesAffectingDvtDevicesWindow_directSSHPort;
- (BOOL)_canRemoteSSH;
- (BOOL)_canDirectSSH;
- (BOOL)_canDirectRsync;
- (BOOL)dvtDevicesWindow_canSSH;
@property(readonly) NSArray *deviceSummaryInternalPropertyDictionaries;
- (id)dvtDevicesWindow_isWirelessEnabled;
- (id)dvtDevicesWindow_rsyncPort;
- (id)dvtDevicesWindow_remoteSSHPort;
- (id)dvtDevicesWindow_directSSHPort;
- (id)_placeholderValue;
@end

