//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSAccessibilityElement.h>

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditor37CodeCoverageRangeAccessibilityElement : NSAccessibilityElement
{
    // Error parsing type: , name: coverageRange
    // Error parsing type: , name: layerProvider
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)accessibilityIdentifier;
- (id)accessibilityTitle;
- (id)accessibilityValue;
- (struct CGRect)accessibilityFrame;

@end

