//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC12SourceEditor17FoldingController : SwiftObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: animationDelegate
    // Error parsing type: , name: delimiterData
    // Error parsing type: , name: foldedRegionDisplay
    // Error parsing type: , name: _foldableRegions
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: allFolds
    // Error parsing type: , name: _cascadedFoldedRanges
    // Error parsing type: , name: lowWaterMarkPosition
    // Error parsing type: , name: highWaterMarkPosition
    // Error parsing type: , name: transientFoldableRegion
    // Error parsing type: , name: isAnimating
    // Error parsing type: , name: transientFoldedRange
}

@end

