//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CAShapeLayer.h>

@interface _TtC12SourceEditorP33_E01BB93BD6F4269A0E3F1B73BF59929419FoldableRegionLayer : CAShapeLayer
{
    // Error parsing type: , name: foldableRegion
    // Error parsing type: , name: lightTheme
    // Error parsing type: , name: lineRange.storage
    // Error parsing type: , name: disclosureDownLayer
    // Error parsing type: , name: disclosureUpLayer
    // Error parsing type: , name: isHighlighted
    // Error parsing type: , name: shapePath
    // Error parsing type: , name: strokeLayer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) struct CGRect frame;
- (id)initWithCoder:(id)arg1;
- (id)initWithLayer:(id)arg1;

@end

