//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerFoundation/DYResource-Protocol.h>

@class NSURL;

@protocol DYFunctionSource <DYResource>
@property(readonly, nonatomic) NSURL *librarySourceDirectoryURL;
@property(readonly, nonatomic) NSURL *fileURL;
@property(readonly, nonatomic) unsigned long long lineNumber;
@end

