//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerFoundation/DYPShaderDebuggerROI-Protocol.h>

@protocol DYPShaderDebuggerROIFragment <DYPShaderDebuggerROI>
@property(readonly, nonatomic) unsigned long long maxSampleId;
@property(readonly, nonatomic) float maxPositionW;
@property(readonly, nonatomic) float maxPositionZ;
@property(readonly, nonatomic) float maxPositionY;
@property(readonly, nonatomic) float maxPositionX;
@property(readonly, nonatomic) unsigned long long minSampleId;
@property(readonly, nonatomic) float minPositionW;
@property(readonly, nonatomic) float minPositionZ;
@property(readonly, nonatomic) float minPositionY;
@property(readonly, nonatomic) float minPositionX;
@end

