//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerFoundation/GPUTraceGroupItem.h>

@interface GPUTraceCommandBufferGroupItem : GPUTraceGroupItem
{
}

- (id)initWithController:(id)arg1 parent:(id)arg2 identifier:(id)arg3 groupType:(unsigned int)arg4 functionIndex:(int)arg5 descText:(id)arg6;

@end

