//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebuggerFoundation/GPUTraceOutlineItem.h>

@class GPUTraceResourceItem;

@interface GPUTraceDependencyResourceItem : GPUTraceOutlineItem
{
    GPUTraceResourceItem *_wrappedResource;
}

@property(nonatomic) __weak GPUTraceResourceItem *wrappedResource; // @synthesize wrappedResource=_wrappedResource;
- (void).cxx_destruct;
- (id)APIItem;
- (id)label;
- (id)initWithResourceItem:(id)arg1 withParent:(id)arg2;

@end

