//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtCV17XCSAdministration16RunRecipeCommandP33_D980F31C533FB11894B0D819402D99A613_StorageClass : SwiftObject
{
    // Error parsing type: , name: _name
    // Error parsing type: , name: _options
}

@end

