//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor36GPUShaderDebuggerImageSelectionValue : NSView
{
    // Error parsing type: , name: scale
    // Error parsing type: , name: offset
    // Error parsing type: , name: selectedPosition
    // Error parsing type: , name: highlightedPosition
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) struct CGPoint offset; // @synthesize offset;
@property(nonatomic) double scale; // @synthesize scale;

@end

