//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtCFC21GPURenderTargetEditor23GPUTraceSourceSubEditorP33_BD4A34EF733ACDEE455B7ABE7841571715setupEditorViewFT_T_L_35ShaderDebuggerLineHighlightProvider : SwiftObject
{
    // Error parsing type: , name: editor
}

@end

