//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC21GPURenderTargetEditor30GPUTraceSourceSubEditorSidebar : SwiftObject
{
    // Error parsing type: , name: marginWidth
    // Error parsing type: , name: widthConstraint
    // Error parsing type: , name: annotationInteractionDelegate
    // Error parsing type: , name: annotationLayoutDelegate
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: contentView
    // Error parsing type: , name: sourceEditorView
}

@end

