//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPURenderTargetEditor/_TtC21GPURenderTargetEditor23GPUTraceSourceSubEditor.h>

@interface _TtC21GPURenderTargetEditor23GPUTraceSourceSubEditor (GPURenderTargetEditor3)
- (unsigned long long)annotationScrollbarMarkerType:(unsigned int)arg1;
- (double)annotationPrecedence:(unsigned int)arg1;
- (id)annotationIcon:(unsigned int)arg1 isFixable:(BOOL)arg2;
- (id)annotationIdentifier:(unsigned int)arg1;
- (id)annotationTheme:(unsigned int)arg1;
@end

