//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSOutlineView;

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor37GPUShaderDebuggerVariableSnapshotView : NSView
{
    // Error parsing type: , name: outlineView
}

- (CDUnknownBlockType).cxx_destruct;
- (void)viewWasDeselectedIn:(id)arg1;
- (void)viewWasSelectedIn:(id)arg1;
@property(nonatomic, readonly) BOOL allowsSelection;
@property(nonatomic, readonly) double preferredLayoutInset;
- (struct CGSize)preferredSizeWithConstrainedBy:(struct CGSize)arg1;
@property(nonatomic, readonly) BOOL canBecomeKeyView;
@property(nonatomic, readonly) BOOL acceptsFirstResponder;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSOutlineView *outlineView; // @synthesize outlineView;

@end

