//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor40GPUTraceShaderProfilerPerformancePieView : NSView
{
    // Error parsing type: , name: segments
    // Error parsing type: , name: trackingArea
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)image;
- (void)drawWithContext:(struct CGContext *)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (BOOL)isFlipped;

// Remaining properties
@property(nonatomic, readonly) BOOL flipped;

@end

