//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC21GPURenderTargetEditor36GPUTraceShaderProfilerPerLineContext : SwiftObject
{
    // Error parsing type: , name: line
    // Error parsing type: , name: lineContent
    // Error parsing type: , name: shaderBinaryCost
    // Error parsing type: , name: shaderProfilerContext
    // Error parsing type: , name: dataType
    // Error parsing type: , name: costPercentage.storage
    // Error parsing type: , name: costAndCountPerInstructionType.storage
    // Error parsing type: , name: disassembledLinesAndData.storage
    // Error parsing type: , name: dataTypeBase
    // Error parsing type: , name: costAndCountPerInstructionTypeBase
    // Error parsing type: , name: showAsAbsoluteTime
    // Error parsing type: , name: absoluteTime
}

@end

