//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor29GPUResourceInfoViewController : NSViewController
{
    // Error parsing type: , name: gridView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)refresh;
- (void)viewDidLoad;
@property(nonatomic, copy) id representedObject;

@end

