//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class GPUTraceResourceItem, _TtC21GPURenderTargetEditor47GPUShaderDebuggerVariableSnapshotViewController;
@protocol DYPShaderDebuggerExecutionHistoryNode;

@protocol _TtP21GPURenderTargetEditor55GPUShaderDebuggerVariableSnapshotViewControllerDelegate_
- (void)selectExecutionHistoryNode:(id <DYPShaderDebuggerExecutionHistoryNode>)arg1 from:(_TtC21GPURenderTargetEditor47GPUShaderDebuggerVariableSnapshotViewController *)arg2;
- (void)navigateToResourceItemWithSnapshotViewController:(_TtC21GPURenderTargetEditor47GPUShaderDebuggerVariableSnapshotViewController *)arg1 resourceItem:(GPUTraceResourceItem *)arg2;
- (void)viewDidResizeWithSnapshotViewController:(_TtC21GPURenderTargetEditor47GPUShaderDebuggerVariableSnapshotViewController *)arg1;
@end

