//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class _TtC21GPURenderTargetEditor40GPUShaderDebuggerIterationViewController;
@protocol DYPShaderDebuggerExecutionHistoryNode;

@protocol _TtP21GPURenderTargetEditor48GPUShaderDebuggerIterationViewControllerDelegate_
- (void)didSelectNodeWithIterationViewController:(_TtC21GPURenderTargetEditor40GPUShaderDebuggerIterationViewController *)arg1 node:(id <DYPShaderDebuggerExecutionHistoryNode>)arg2;
@end

