//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPURenderTargetEditor/DYPShaderDebuggerROI-Protocol.h>

@protocol DYPShaderDebuggerROIKernel <DYPShaderDebuggerROI>
@property(nonatomic, readonly) unsigned long long maxThreadPositionZ;
@property(nonatomic, readonly) unsigned long long maxThreadPositionY;
@property(nonatomic, readonly) unsigned long long maxThreadPositionX;
@property(nonatomic, readonly) unsigned long long minThreadPositionZ;
@property(nonatomic, readonly) unsigned long long minThreadPositionY;
@property(nonatomic, readonly) unsigned long long minThreadPositionX;
@end

