//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPURenderTargetEditor/DYPShaderDebuggerThread-Protocol.h>

@protocol DYPShaderDebuggerThreadFragment <DYPShaderDebuggerThread>
@property(nonatomic, readonly) BOOL isFrontMost;
@property(nonatomic, readonly) unsigned long long sampleId;
@property(nonatomic, readonly) float positionW;
@property(nonatomic, readonly) float positionZ;
@property(nonatomic, readonly) float positionY;
@property(nonatomic, readonly) float positionX;
@end

