//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPURenderTargetEditor/GPUGVRank.h>

__attribute__((visibility("hidden")))
@interface GPUGVHorizontalRank : GPUGVRank
{
}

- (void)centerNode:(id)arg1 at:(double)arg2;
- (void)centerNodesWithRespectoTo:(id)arg1;
- (struct CGSize)sizeForDummy;
- (double)height;
- (double)width;
- (id)initWithSeparation:(struct CGSize)arg1;

@end

