//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpriteKit/SKSpriteNode.h>

@class DVTFuture, DVTObservingToken, GPUDebuggerDependencyViewerTextureCache, NSColor, NSDictionary, NSFont, NSString, NSView;

__attribute__((visibility("hidden")))
@interface GPUTraceSKTruncatedLabel : SKSpriteNode
{
    GPUDebuggerDependencyViewerTextureCache *_textureCache;
    DVTObservingToken *_themeObserver;
    BOOL _appearanceChangedFirstTime;
    double _magnification;
    NSString *_previousConfiguration;
    NSDictionary *_configurations;
    double _fontWeight;
    BOOL _truncated;
    NSString *_labelText;
    NSColor *_textColor;
    NSColor *_backgroundColor;
    double _maxWidth;
    double _fullLabelLength;
    double _labelHeight;
    NSFont *_font;
    NSView *_appearanceView;
    DVTFuture *_textureFuture;
}

@property(retain) DVTFuture *textureFuture; // @synthesize textureFuture=_textureFuture;
@property(readonly, nonatomic) __weak NSView *appearanceView; // @synthesize appearanceView=_appearanceView;
@property(readonly, nonatomic) NSFont *font; // @synthesize font=_font;
@property(nonatomic) double labelHeight; // @synthesize labelHeight=_labelHeight;
@property(nonatomic) double fullLabelLength; // @synthesize fullLabelLength=_fullLabelLength;
@property(nonatomic) BOOL truncated; // @synthesize truncated=_truncated;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(readonly, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(copy, nonatomic) NSString *labelText; // @synthesize labelText=_labelText;
@property(nonatomic) double magnification; // @synthesize magnification=_magnification;
- (void).cxx_destruct;
- (void)_rebuildTextureForConfiguration:(id)arg1;
- (id)_labelAttributes;
- (id)_cacheKey;
- (void)setTexture:(id)arg1;
- (id)_buildTextLayer;
- (void)forceTextureRebuild;
- (void)updateTextColor:(id)arg1 withBackgroundColor:(id)arg2;
- (void)updateTextColor:(id)arg1;
- (void)_updateLabelText;
- (void)registerForThemeChange:(id)arg1;
- (void)dealloc;
- (id)initWithFont:(id)arg1 weight:(double)arg2 configurations:(id)arg3 withTextureCache:(id)arg4;

@end

