//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class GPUSharedTabUIState, GPUTraceDocument, GPUTraceMainEditor, GPUTraceOutlineItem, GPUTraceStorage, NSDictionary;

@interface GPUTraceSubEditor : NSViewController
{
    GPUTraceDocument *_document;
    GPUTraceStorage *_storage;
    NSDictionary *_userInfo;
}

@property(copy) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) GPUTraceStorage *storage; // @synthesize storage=_storage;
@property(retain, nonatomic) GPUTraceDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (id)documentLocationsForItems:(id)arg1;
- (void)dumpImages:(id)arg1 asRaw:(BOOL)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)takeFocus;
- (void)setRepresentedObject:(id)arg1 userInfo:(id)arg2;
@property(retain) GPUTraceOutlineItem *representedObject; // @dynamic representedObject;
- (BOOL)findBarSupported;
- (void)handleNotification:(id)arg1;
@property(readonly, nonatomic) __weak GPUSharedTabUIState *sharedUIStateObj;

// Remaining properties
@property(readonly) GPUTraceMainEditor *parentViewController; // @dynamic parentViewController;

@end

