//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpriteKit/SKNode.h>

@class GPUDebuggerDependencyViewerTextureCache, NSMutableArray;

__attribute__((visibility("hidden")))
@interface GPUTraceStatBox : SKNode
{
    NSMutableArray *_lines;
    unsigned long long _anchor;
    GPUDebuggerDependencyViewerTextureCache *_textureCache;
}

- (void).cxx_destruct;
- (unsigned long long)numberOfLines;
- (void)highlight:(BOOL)arg1;
- (void)addBadgeLine:(id)arg1;
- (void)addStatWithTitle:(id)arg1 andLabel:(id)arg2;
- (double)height;
- (id)initWithAnchor:(unsigned long long)arg1 textureCache:(id)arg2;

@end

