//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpriteKit/SKNode.h>

@class SKShapeNode;

__attribute__((visibility("hidden")))
@interface GPUTraceSKHighlight : SKNode
{
    SKShapeNode *_highlight;
    struct CGRect _rect;
    struct CGRect _highlightRect;
}

- (void).cxx_destruct;
- (void)draw;
- (id)initWithRect:(struct CGRect)arg1 withHighlightRect:(struct CGRect)arg2;
- (id)initWithRect:(struct CGRect)arg1 withInset:(struct CGSize)arg2;

@end

