//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DYPPerformanceBottleneck, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface GPUTracePerformanceBottleneck : NSObject
{
    DYPPerformanceBottleneck *_bottleneck;
    unsigned long long _severity;
    NSString *_issue;
    NSArray *_associatedItems;
}

@property(retain, nonatomic) NSArray *associatedItems; // @synthesize associatedItems=_associatedItems;
@property(retain, nonatomic) NSString *issue; // @synthesize issue=_issue;
@property(nonatomic) unsigned long long severity; // @synthesize severity=_severity;
@property(retain, nonatomic) DYPPerformanceBottleneck *bottleneck; // @synthesize bottleneck=_bottleneck;
- (void).cxx_destruct;

@end

