//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPURenderTargetEditor/GPUGVNode.h>

@class GPUTraceGroupItem, NSString;
@protocol DYPDependencyGraphCommandBufferNode, DYPDependencyGraphEncoderNode;

__attribute__((visibility("hidden")))
@interface GVBaseNode : GPUGVNode
{
    id <DYPDependencyGraphEncoderNode> _dependencyNode;
    id <DYPDependencyGraphCommandBufferNode> _dependencyGraph;
    GPUTraceGroupItem *_outlineItem;
    double _zoomLevel;
    NSString *_uuid;
}

@property(readonly, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) double zoomLevel; // @synthesize zoomLevel=_zoomLevel;
@property(nonatomic) __weak GPUTraceGroupItem *outlineItem; // @synthesize outlineItem=_outlineItem;
- (void).cxx_destruct;
- (struct CGRect)frame;
- (struct CGSize)size;
- (id)dependencyGraph;
- (id)dependencyNode;
- (id)initWithOutlineItem:(id)arg1;

@end

