//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPURenderTargetEditor/GVBaseNode.h>

__attribute__((visibility("hidden")))
@interface GVGraphResourceNode : GVBaseNode
{
    unsigned int _resourceType;
    unsigned long long _resourceId;
}

@property(readonly, nonatomic) unsigned int resourceType; // @synthesize resourceType=_resourceType;
@property(nonatomic) unsigned long long resourceId; // @synthesize resourceId=_resourceId;
- (id)initWithOutlineItem:(id)arg1 andResourceId:(unsigned long long)arg2 resourceType:(unsigned int)arg3;

@end

