//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 20 2018 10:52:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUTools/DYPluginDirectoryProvider.h>

@class NSString;

@interface DYToolsPluginDirectoryProvider : DYPluginDirectoryProvider
{
    BOOL _includePrivatePlugins;
    NSString *_toolsPluginBundle;
    NSString *_toolsPrivatePluginBundle;
}

- (void)enumerateDirectories:(CDUnknownBlockType)arg1;
- (id)initWithDeveloperPath:(id)arg1 includePrivatePlugins:(BOOL)arg2;
- (id)init;

@end

